<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The event payload. */
readonly class ActionAuthenticationDeniedData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the action endpoint. */
        public string $actionEndpointId,
        /** The ID of the action execution. */
        public string $actionExecutionId,
        /** The type of action that was denied. */
        public string $type,
        /** The verdict of the action. */
        public string $verdict,
        /** The ID of the user. */
        public string $userId,
        /** The ID of the organization. */
        public ?string $organizationId,
        /** The email address of the user. */
        public string $email,
        /** The IP address of the request. */
        public ?string $ipAddress,
        /** The user agent of the request. */
        public ?string $userAgent,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            actionEndpointId: $data['action_endpoint_id'],
            actionExecutionId: $data['action_execution_id'],
            type: $data['type'] ?? 'authentication',
            verdict: $data['verdict'] ?? 'Deny',
            userId: $data['user_id'],
            organizationId: $data['organization_id'] ?? null,
            email: $data['email'],
            ipAddress: $data['ip_address'] ?? null,
            userAgent: $data['user_agent'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'action_endpoint_id' => $this->actionEndpointId,
            'action_execution_id' => $this->actionExecutionId,
            'type' => $this->type,
            'verdict' => $this->verdict,
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'email' => $this->email,
            'ip_address' => $this->ipAddress,
            'user_agent' => $this->userAgent,
        ];
    }
}
