<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum AgentRegistrationCreatedDataMethod: string
{
    case Anonymous = 'anonymous';
    case ServiceAuth = 'service_auth';
    case IdJag = 'id_jag';
}
