<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The agent identity associated with this registration. */
readonly class AgentRegistrationAgentIdentity implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the agent identity. */
        public string $id,
        /** Identifier of the AuthKit user the agent identity is bound to, or `null` when the agent is not associated with a user. */
        public ?string $userlandUserId,
        /** The timestamp when the agent identity was created. */
        public \DateTimeImmutable $createdAt,
        /** The timestamp when the agent identity was last updated. */
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            userlandUserId: $data['userland_user_id'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'userland_user_id' => $this->userlandUserId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
