<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The user to attach to the claim attempt, identified by email and external ID. */
readonly class AgentAdminLinkClaimAttemptToExternalUserRequestUser implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The email address of the user. */
        public string $email,
        /** The external ID of the user. */
        public string $externalId,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'],
            externalId: $data['external_id'],
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'external_id' => $this->externalId,
        ];
    }
}
