<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AgentInstanceSession implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the agent instance session object. */
        public string $object,
        /** Unique identifier of the agent instance session. */
        public string $id,
        /** The agent instance the session belongs to. */
        public string $agentInstanceId,
        /** Derived from `revoked_at` and `expires_at` at read time; a revoked session stays `revoked` even after it expires. */
        public UserSessionsStatus $status,
        /** Timestamp when the session expires. */
        public \DateTimeImmutable $expiresAt,
        /** Timestamp when the session was revoked; `null` if it has not been revoked. */
        public ?\DateTimeImmutable $revokedAt,
        /** Timestamp when the session was created. */
        public \DateTimeImmutable $createdAt,
        /** Timestamp when the session was last updated. */
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'agent_instance_session',
            id: $data['id'],
            agentInstanceId: $data['agent_instance_id'],
            status: UserSessionsStatus::from($data['status']),
            expiresAt: new \DateTimeImmutable($data['expires_at']),
            revokedAt: isset($data['revoked_at']) ? new \DateTimeImmutable($data['revoked_at']) : null,
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'agent_instance_id' => $this->agentInstanceId,
            'status' => $this->status->value,
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'revoked_at' => $this->revokedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
