<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AgentInstance implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the agent instance object. */
        public string $object,
        /** Unique identifier of the agent instance. */
        public string $id,
        /** The blueprint this instance was minted from. */
        public string $agentBlueprintId,
        /** The organization the instance acts within. */
        public string $organizationId,
        /** The organization membership of the delegating user; `null` for autonomous instances. */
        public ?string $organizationMembershipId,
        /** Whether the instance acts on behalf of a specific user (`delegated`) or as itself (`autonomous`). */
        public AgentInstanceType $type,
        /** Timestamp when the agent instance was created. */
        public \DateTimeImmutable $createdAt,
        /** Timestamp when the agent instance was last updated. */
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'agent_instance',
            id: $data['id'],
            agentBlueprintId: $data['agent_blueprint_id'],
            organizationId: $data['organization_id'],
            organizationMembershipId: $data['organization_membership_id'] ?? null,
            type: AgentInstanceType::from($data['type']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'agent_blueprint_id' => $this->agentBlueprintId,
            'organization_id' => $this->organizationId,
            'organization_membership_id' => $this->organizationMembershipId,
            'type' => $this->type->value,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
