<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The event payload. */
readonly class ApiKeyRevokedData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the API key object. */
        public string $object,
        /** Unique identifier of the API key. */
        public string $id,
        /** The owner of the API key. */
        public ApiKeyRevokedDataOwner|UserApiKeyRevokedDataOwner $owner,
        /** The name of the API key. */
        public string $name,
        /** The obfuscated value of the API key. */
        public string $obfuscatedValue,
        /** The timestamp when the API key was last used. */
        public ?string $lastUsedAt,
        /**
         * The permissions granted to the API key.
         * @var array<string>
         */
        public array $permissions,
        /** The timestamp when the API key was created. */
        public string $createdAt,
        /** The timestamp when the API key was last updated. */
        public string $updatedAt,
        /** Timestamp when the API Key expires. Null means the key does not expire. */
        public ?\DateTimeImmutable $expiresAt = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'api_key',
            id: $data['id'],
            owner: match ($data['owner']['type'] ?? null) {
                'organization' => ApiKeyRevokedDataOwner::fromArray($data['owner']), 'user' => UserApiKeyRevokedDataOwner::fromArray($data['owner']), default => throw new \UnexpectedValueException(sprintf('Unknown type: %s', json_encode($data['owner']['type'] ?? null)))
            },
            name: $data['name'],
            obfuscatedValue: $data['obfuscated_value'],
            lastUsedAt: $data['last_used_at'] ?? null,
            permissions: $data['permissions'],
            createdAt: $data['created_at'],
            updatedAt: $data['updated_at'],
            expiresAt: isset($data['expires_at']) ? new \DateTimeImmutable($data['expires_at']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'owner' => $this->owner->toArray(),
            'name' => $this->name,
            'obfuscated_value' => $this->obfuscatedValue,
            'last_used_at' => $this->lastUsedAt,
            'permissions' => $this->permissions,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
            'expires_at' => $this->expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
