<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ApiKeyValidationResponse implements \JsonSerializable
{
    public function __construct(
        public ?ApiKey $apiKey,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            apiKey: ApiKey::fromArray($data['api_key']),
        );
    }

    public function toArray(): array
    {
        return [
            'api_key' => $this->apiKey?->toArray(),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
