<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ApiKeyValidationResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?ApiKeyValidationResponseApiKey $apiKey,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            apiKey: isset($data['api_key']) ? ApiKeyValidationResponseApiKey::fromArray($data['api_key']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'api_key' => $this->apiKey?->toArray(),
        ];
    }
}
