<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ApiKeyWithValue implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $object,
        public string $id,
        public ApiKeyWithValueOwner $owner,
        public string $name,
        public string $obfuscatedValue,
        public ?string $lastUsedAt,
        public array $permissions,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        public string $value,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            owner: ApiKeyWithValueOwner::fromArray($data['owner']),
            name: $data['name'],
            obfuscatedValue: $data['obfuscated_value'],
            lastUsedAt: $data['last_used_at'] ?? null,
            permissions: $data['permissions'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            value: $data['value'],
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'owner' => $this->owner->toArray(),
            'name' => $this->name,
            'obfuscated_value' => $this->obfuscatedValue,
            'last_used_at' => $this->lastUsedAt,
            'permissions' => $this->permissions,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'value' => $this->value,
        ];
    }
}
