<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AssignRole implements \JsonSerializable
{
    public function __construct(
        public string $roleSlug,
        public ?string $resourceId = null,
        public ?string $resourceExternalId = null,
        public ?string $resourceTypeSlug = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            roleSlug: $data['role_slug'],
            resourceId: $data['resource_id'] ?? null,
            resourceExternalId: $data['resource_external_id'] ?? null,
            resourceTypeSlug: $data['resource_type_slug'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'role_slug' => $this->roleSlug,
            'resource_id' => $this->resourceId,
            'resource_external_id' => $this->resourceExternalId,
            'resource_type_slug' => $this->resourceTypeSlug,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
