<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogConfiguration implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the Organization. */
        public string $organizationId,
        /** The number of days Audit Log events will be retained before being permanently deleted. */
        public int $retentionPeriodInDays,
        /** The current state of the audit log configuration for the organization. */
        public AuditLogConfigurationState $state,
        /** The Audit Log Stream currently configured for the organization, if any. */
        public ?AuditLogConfigurationLogStream $logStream = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            organizationId: $data['organization_id'],
            retentionPeriodInDays: $data['retention_period_in_days'],
            state: AuditLogConfigurationState::from($data['state']),
            logStream: isset($data['log_stream']) ? AuditLogConfigurationLogStream::fromArray($data['log_stream']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'retention_period_in_days' => $this->retentionPeriodInDays,
            'state' => $this->state->value,
            'log_stream' => $this->logStream?->toArray(),
        ];
    }
}
