<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogExportCreation implements \JsonSerializable
{
    public function __construct(
        public string $organizationId,
        public string $rangeStart,
        public string $rangeEnd,
        public ?array $actions = null,
        public ?array $actors = null,
        public ?array $actorNames = null,
        public ?array $actorIds = null,
        public ?array $targets = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            organizationId: $data['organization_id'],
            rangeStart: $data['range_start'],
            rangeEnd: $data['range_end'],
            actions: $data['actions'] ?? null,
            actors: $data['actors'] ?? null,
            actorNames: $data['actor_names'] ?? null,
            actorIds: $data['actor_ids'] ?? null,
            targets: $data['targets'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'range_start' => $this->rangeStart,
            'range_end' => $this->rangeEnd,
            'actions' => $this->actions,
            'actors' => $this->actors,
            'actor_names' => $this->actorNames,
            'actor_ids' => $this->actorIds,
            'targets' => $this->targets,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
