<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The Audit Log Stream currently configured for the organization, if any. */
readonly class AuditLogConfigurationLogStream implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the Audit Log Stream. */
        public string $id,
        /** The type of the Audit Log Stream destination. */
        public AuditLogConfigurationLogStreamType $type,
        /** The current state of the Audit Log Stream. */
        public AuditLogConfigurationLogStreamState $state,
        /** ISO-8601 timestamp of when the last event was successfully synced, or null if no events have been synced. */
        public ?string $lastSyncedAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            type: AuditLogConfigurationLogStreamType::from($data['type']),
            state: AuditLogConfigurationLogStreamState::from($data['state']),
            lastSyncedAt: $data['last_synced_at'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type->value,
            'state' => $this->state->value,
            'last_synced_at' => $this->lastSyncedAt,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
