<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogEvent implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Identifier of what happened. */
        public string $action,
        /** ISO-8601 value of when the action occurred. */
        public \DateTimeImmutable $occurredAt,
        /** The entity that performed the action. */
        public AuditLogEventActor $actor,
        /**
         * The resources affected by the action.
         * @var array<\WorkOS\Resource\AuditLogEventTarget>
         */
        public array $targets,
        /** Additional context about where and how the action occurred. */
        public AuditLogEventContext $context,
        /**
         * Additional data associated with the event or entity.
         * @var array<string, string|float|bool>|null
         */
        public ?array $metadata = null,
        /** What schema version the event is associated with. */
        public ?int $version = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            action: $data['action'],
            occurredAt: new \DateTimeImmutable($data['occurred_at']),
            actor: AuditLogEventActor::fromArray($data['actor']),
            targets: array_map(fn ($item) => AuditLogEventTarget::fromArray($item), $data['targets']),
            context: AuditLogEventContext::fromArray($data['context']),
            metadata: $data['metadata'] ?? null,
            version: $data['version'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'action' => $this->action,
            'occurred_at' => $this->occurredAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'actor' => $this->actor->toArray(),
            'targets' => array_map(fn ($item) => $item->toArray(), $this->targets),
            'context' => $this->context->toArray(),
            'metadata' => $this->metadata,
            'version' => $this->version,
        ];
    }
}
