<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum AuditLogsOrder: string
{
    case Normal = 'normal';
    case Desc = 'desc';
    case Asc = 'asc';
}
