<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogSchemaActor implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public array $metadata,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            metadata: $data['metadata'],
        );
    }

    public function toArray(): array
    {
        return [
            'metadata' => $this->metadata,
        ];
    }
}
