<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogSchemaTarget implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The type of the target resource. */
        public string $type,
        /**
         * Optional JSON schema for target metadata.
         * @var array<string, mixed>|null
         */
        public ?array $metadata = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'],
            metadata: $data['metadata'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'type' => $this->type,
            'metadata' => $this->metadata,
        ];
    }
}
