<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogEventIngestion implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $organizationId,
        public AuditLogEvent $event,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            organizationId: $data['organization_id'],
            event: AuditLogEvent::fromArray($data['event']),
        );
    }

    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'event' => $this->event->toArray(),
        ];
    }
}
