<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogsRetention implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The number of days Audit Log events will be retained before being permanently deleted. Valid values are 30 through 330 in 30-day increments and 365 through 3650 in 365-day increments. */
        public ?int $retentionPeriodInDays,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            retentionPeriodInDays: $data['retention_period_in_days'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'retention_period_in_days' => $this->retentionPeriodInDays,
        ];
    }
}
