<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuditLogConfigurationLogStream implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public AuditLogConfigurationLogStreamType $type,
        public AuditLogConfigurationLogStreamState $state,
        public ?string $lastSyncedAt,
        public \DateTimeImmutable $createdAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            type: AuditLogConfigurationLogStreamType::from($data['type']),
            state: AuditLogConfigurationLogStreamState::from($data['state']),
            lastSyncedAt: $data['last_synced_at'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type->value,
            'state' => $this->state->value,
            'last_synced_at' => $this->lastSyncedAt,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
