<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthenticationFactorsCreateRequest implements \JsonSerializable
{
    public function __construct(
        public AuthenticationFactorsCreateRequestType $type,
        public ?string $phoneNumber = null,
        public ?string $totpIssuer = null,
        public ?string $totpUser = null,
        public ?string $userId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            type: AuthenticationFactorsCreateRequestType::tryFrom($data['type']) ?? $data['type'],
            phoneNumber: $data['phone_number'] ?? null,
            totpIssuer: $data['totp_issuer'] ?? null,
            totpUser: $data['totp_user'] ?? null,
            userId: $data['user_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'type' => $this->type->value,
            'phone_number' => $this->phoneNumber,
            'totp_issuer' => $this->totpIssuer,
            'totp_user' => $this->totpUser,
            'user_id' => $this->userId,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
