<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthorizationCheck implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $authorized,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            authorized: $data['authorized'],
        );
    }

    public function toArray(): array
    {
        return [
            'authorized' => $this->authorized,
        ];
    }
}
