<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum AuthenticationFactorEnrolledType: string
{
    case GenericOtp = 'generic_otp';
    case Sms = 'sms';
    case Totp = 'totp';
    case Webauthn = 'webauthn';
}
