<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthorizationResource implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the Resource object. */
        public string $object,
        /** A human-readable name for the Resource. */
        public string $name,
        /** An optional description of the Resource. */
        public ?string $description,
        /** The ID of the organization that owns the resource. */
        public string $organizationId,
        /** The ID of the parent resource, if this resource is nested. */
        public ?string $parentResourceId,
        /** The unique ID of the Resource. */
        public string $id,
        /** An identifier you provide to reference the resource in your system. */
        public string $externalId,
        /** The slug of the resource type this resource belongs to. */
        public string $resourceTypeSlug,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'authorization_resource',
            name: $data['name'],
            description: $data['description'] ?? null,
            organizationId: $data['organization_id'],
            parentResourceId: $data['parent_resource_id'] ?? null,
            id: $data['id'],
            externalId: $data['external_id'],
            resourceTypeSlug: $data['resource_type_slug'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'name' => $this->name,
            'description' => $this->description,
            'organization_id' => $this->organizationId,
            'parent_resource_id' => $this->parentResourceId,
            'id' => $this->id,
            'external_id' => $this->externalId,
            'resource_type_slug' => $this->resourceTypeSlug,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
