<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthenticationFactorEnrolledTotp implements \JsonSerializable
{
    public function __construct(
        public string $issuer,
        public string $user,
        public string $secret,
        public string $qrCode,
        public string $uri,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            issuer: $data['issuer'],
            user: $data['user'],
            secret: $data['secret'],
            qrCode: $data['qr_code'],
            uri: $data['uri'],
        );
    }

    public function toArray(): array
    {
        return [
            'issuer' => $this->issuer,
            'user' => $this->user,
            'secret' => $this->secret,
            'qr_code' => $this->qrCode,
            'uri' => $this->uri,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
