<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthorizedConnectApplicationListData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the authorized connect application object. */
        public string $object,
        /** The unique ID of the authorized connect application. */
        public string $id,
        /**
         * The scopes granted by the user to the application.
         * @var array<string>
         */
        public array $grantedScopes,
        public ConnectApplication $application,
        /** The OAuth resource associated with the authorized connect application, if one was requested. */
        public ?string $oauthResource = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            grantedScopes: $data['granted_scopes'],
            application: ConnectApplication::fromArray($data['application']),
            oauthResource: $data['oauth_resource'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'granted_scopes' => $this->grantedScopes,
            'application' => $this->application->toArray(),
            'oauth_resource' => $this->oauthResource,
        ];
    }
}
