<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthenticateResponseImpersonator implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $email,
        public ?string $reason,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'],
            reason: $data['reason'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'reason' => $this->reason,
        ];
    }
}
