<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum AuthorizationAssignment: string
{
    case Direct = 'direct';
    case Indirect = 'indirect';
}
