<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthenticationChallengeVerifyResponse implements \JsonSerializable
{
    public function __construct(
        public AuthenticationChallenge $challenge,
        public bool $valid,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            challenge: AuthenticationChallenge::fromArray($data['challenge']),
            valid: $data['valid'],
        );
    }

    public function toArray(): array
    {
        return [
            'challenge' => $this->challenge->toArray(),
            'valid' => $this->valid,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
