<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class AuthenticationChallenge implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the authentication challenge object. */
        public string $object,
        /** The unique ID of the authentication challenge. */
        public string $id,
        /** The unique ID of the authentication factor the challenge belongs to. */
        public string $authenticationFactorId,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
        /** The timestamp when the challenge will expire. Does not apply to TOTP factors. */
        public ?\DateTimeImmutable $expiresAt = null,
        /** The one-time code for the challenge. */
        public ?string $code = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            authenticationFactorId: $data['authentication_factor_id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            expiresAt: isset($data['expires_at']) ? new \DateTimeImmutable($data['expires_at']) : null,
            code: $data['code'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'authentication_factor_id' => $this->authenticationFactorId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'expires_at' => $this->expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'code' => $this->code,
        ];
    }
}
