<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ClientApiToken implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the organization to scope the Client API token to. */
        public string $organizationId,
        /** The ID of the user to issue the Client API token for. */
        public string $userId,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            organizationId: $data['organization_id'],
            userId: $data['user_id'],
        );
    }

    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'user_id' => $this->userId,
        ];
    }
}
