<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ConfirmEmailChange implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The one-time code used to confirm the email change. */
        public string $code,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            code: $data['code'],
        );
    }

    public function toArray(): array
    {
        return [
            'code' => $this->code,
        ];
    }
}
