<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ConnectApplicationOAuthRedirectUris implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The redirect URI for the application. */
        public string $uri,
        /** Whether this is the default redirect URI. */
        public bool $default,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            uri: $data['uri'],
            default: $data['default'],
        );
    }

    public function toArray(): array
    {
        return [
            'uri' => $this->uri,
            'default' => $this->default,
        ];
    }
}
