<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The event payload. */
readonly class ConnectionSAMLCertificateRenewalRequiredData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The connection with the expiring certificate. */
        public ConnectionSAMLCertificateRenewalRequiredDataConnection $connection,
        /** The SAML certificate details. */
        public ConnectionSAMLCertificateRenewalRequiredDataCertificate $certificate,
        /** The number of days until the certificate expires. */
        public int $daysUntilExpiry,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            connection: ConnectionSAMLCertificateRenewalRequiredDataConnection::fromArray($data['connection']),
            certificate: ConnectionSAMLCertificateRenewalRequiredDataCertificate::fromArray($data['certificate']),
            daysUntilExpiry: $data['days_until_expiry'],
        );
    }

    public function toArray(): array
    {
        return [
            'connection' => $this->connection->toArray(),
            'certificate' => $this->certificate->toArray(),
            'days_until_expiry' => $this->daysUntilExpiry,
        ];
    }
}
