<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The event payload. */
readonly class ConnectionSAMLCertificateRenewedData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The connection with the renewed certificate. */
        public ConnectionSAMLCertificateRenewedDataConnection $connection,
        /** The renewed SAML certificate details. */
        public ConnectionSAMLCertificateRenewedDataCertificate $certificate,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $renewedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            connection: ConnectionSAMLCertificateRenewedDataConnection::fromArray($data['connection']),
            certificate: ConnectionSAMLCertificateRenewedDataCertificate::fromArray($data['certificate']),
            renewedAt: new \DateTimeImmutable($data['renewed_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'connection' => $this->connection->toArray(),
            'certificate' => $this->certificate->toArray(),
            'renewed_at' => $this->renewedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
