<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Connection implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public string $id,
        public ConnectionType $connectionType,
        public string $name,
        public ConnectionState $state,
        public ConnectionStatus $status,
        public array $domains,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        public ?string $organizationId = null,
        public ?ConnectionOption $options = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            connectionType: ConnectionType::tryFrom($data['connection_type']) ?? $data['connection_type'],
            name: $data['name'],
            state: ConnectionState::tryFrom($data['state']) ?? $data['state'],
            status: ConnectionStatus::tryFrom($data['status']) ?? $data['status'],
            domains: array_map(fn ($item) => ConnectionDomain::fromArray($item), $data['domains']),
            createdAt: new \DateTimeImmutable($data['created_at'] ?? 'now'),
            updatedAt: new \DateTimeImmutable($data['updated_at'] ?? 'now'),
            organizationId: $data['organization_id'] ?? null,
            options: isset($data['options']) ? ConnectionOption::fromArray($data['options']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'connection_type' => $this->connectionType->value,
            'name' => $this->name,
            'state' => $this->state->value,
            'status' => $this->status->value,
            'domains' => array_map(fn ($item) => $item->toArray(), $this->domains),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'organization_id' => $this->organizationId,
            'options' => $this->options?->toArray(),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
