<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum ConnectionDeletedDataState: string
{
    case Draft = 'draft';
    case Active = 'active';
    case Validating = 'validating';
    case Inactive = 'inactive';
    case Deleting = 'deleting';
}
