<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ConnectionDomain implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier for the Connection Domain. */
        public string $id,
        /** Distinguishes the Connection Domain object. */
        public string $object,
        /** The domain value. */
        public string $domain,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            object: $data['object'],
            domain: $data['domain'],
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'object' => $this->object,
            'domain' => $this->domain,
        ];
    }
}
