<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ConnectApplicationOAuth implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the connect application object. */
        public string $object,
        /** The unique ID of the connect application. */
        public string $id,
        /** The client ID of the connect application. */
        public string $clientId,
        /** A description of the connect application. */
        public ?string $description,
        /** The name of the connect application. */
        public string $name,
        /**
         * The scopes available for this application.
         * @var array<string>
         */
        public array $scopes,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
        /** The type of the application. */
        public string $applicationType,
        /**
         * The redirect URIs configured for this application.
         * @var array<\WorkOS\Resource\ConnectApplicationOAuthRedirectUris>
         */
        public array $redirectUris,
        /** Whether the application uses PKCE for authorization. */
        public bool $usesPkce,
        /** Whether the application is a first-party application. */
        public bool $isFirstParty,
        /** Whether the application was dynamically registered. */
        public ?bool $wasDynamicallyRegistered = null,
        /** The ID of the organization the application belongs to. */
        public ?string $organizationId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'connect_application',
            id: $data['id'],
            clientId: $data['client_id'],
            description: $data['description'] ?? null,
            name: $data['name'],
            scopes: $data['scopes'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            applicationType: $data['application_type'] ?? 'oauth',
            redirectUris: array_map(fn ($item) => ConnectApplicationOAuthRedirectUris::fromArray($item), $data['redirect_uris']),
            usesPkce: $data['uses_pkce'],
            isFirstParty: $data['is_first_party'],
            wasDynamicallyRegistered: $data['was_dynamically_registered'] ?? null,
            organizationId: $data['organization_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'client_id' => $this->clientId,
            'description' => $this->description,
            'name' => $this->name,
            'scopes' => $this->scopes,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'application_type' => $this->applicationType,
            'redirect_uris' => array_map(fn ($item) => $item->toArray(), $this->redirectUris),
            'uses_pkce' => $this->usesPkce,
            'is_first_party' => $this->isFirstParty,
            'was_dynamically_registered' => $this->wasDynamicallyRegistered,
            'organization_id' => $this->organizationId,
        ];
    }
}
