<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ConnectApplication implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the connect application object. */
        public string $object,
        /** The unique ID of the connect application. */
        public string $id,
        /** The client ID of the connect application. */
        public string $clientId,
        /** A description of the connect application. */
        public ?string $description,
        /** The name of the connect application. */
        public string $name,
        /**
         * The scopes available for this application.
         * @var array<string>
         */
        public array $scopes,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            clientId: $data['client_id'],
            description: $data['description'] ?? null,
            name: $data['name'],
            scopes: $data['scopes'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'client_id' => $this->clientId,
            'description' => $this->description,
            'name' => $this->name,
            'scopes' => $this->scopes,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
