<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateWaitlistEntry implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The email address of the user joining the waitlist. */
        public string $email,
        /**
         * Object containing additional key/value pairs collected with the waitlist entry. Supports up to 50 string pairs, with keys up to 40 characters and values up to 600 characters. Values are user-provided — treat them as untrusted input when rendering or exporting.
         * @var array<string, string>|null
         */
        public ?array $additionalFields = null,
        /** Whether to send the waitlist confirmation email to the user. Defaults to `false`. No email is sent when the waitlist confirmation email is disabled in the environment, even if `send_confirmation_email` is `true`. */
        public ?bool $sendConfirmationEmail = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'],
            additionalFields: $data['additional_fields'] ?? null,
            sendConfirmationEmail: $data['send_confirmation_email'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'additional_fields' => $this->additionalFields,
            'send_confirmation_email' => $this->sendConfirmationEmail,
        ];
    }
}
