<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateMagicCodeAndReturn implements \JsonSerializable
{
    public function __construct(
        public string $email,
        public ?string $invitationToken = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'],
            invitationToken: $data['invitation_token'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'invitation_token' => $this->invitationToken,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
