<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateWebhookEndpoint implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The HTTPS URL where webhooks will be sent. */
        public string $endpointUrl,
        /** The events that the Webhook Endpoint is subscribed to. */
        public array $events,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            endpointUrl: $data['endpoint_url'],
            events: $data['events'],
        );
    }

    public function toArray(): array
    {
        return [
            'endpoint_url' => $this->endpointUrl,
            'events' => $this->events,
        ];
    }
}
