<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreatePasswordResetToken implements \JsonSerializable
{
    public function __construct(
        public string $email,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'],
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
