<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateRedirectUri implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $uri,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            uri: $data['uri'],
        );
    }

    public function toArray(): array
    {
        return [
            'uri' => $this->uri,
        ];
    }
}
