<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum CreateUserPasswordSaltPosition: string
{
    case Prefix = 'prefix';
    case Suffix = 'suffix';
}
