<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateUser implements \JsonSerializable
{
    public function __construct(
        public string $email,
        public ?string $password = null,
        public ?string $passwordHash = null,
        public ?CreateUserPasswordHashType $passwordHashType = null,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?bool $emailVerified = null,
        public ?array $metadata = null,
        public ?string $externalId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'],
            password: $data['password'] ?? null,
            passwordHash: $data['password_hash'] ?? null,
            passwordHashType: isset($data['password_hash_type']) ? CreateUserPasswordHashType::tryFrom($data['password_hash_type']) ?? $data['password_hash_type'] : null,
            firstName: $data['first_name'] ?? null,
            lastName: $data['last_name'] ?? null,
            emailVerified: $data['email_verified'] ?? null,
            metadata: $data['metadata'] ?? null,
            externalId: $data['external_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'password' => $this->password,
            'password_hash' => $this->passwordHash,
            'password_hash_type' => $this->passwordHashType instanceof \BackedEnum ? $this->passwordHashType->value : $this->passwordHashType,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'email_verified' => $this->emailVerified,
            'metadata' => $this->metadata,
            'external_id' => $this->externalId,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
