<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum CreateUserPasswordHashType: string
{
    case Bcrypt = 'bcrypt';
    case FirebaseScrypt = 'firebase-scrypt';
    case Ssha = 'ssha';
    case Scrypt = 'scrypt';
    case Pbkdf2 = 'pbkdf2';
    case Argon2 = 'argon2';
}
