<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateOAuthApplication implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The name of the application. */
        public string $name,
        /** The type of application to create. */
        public string $applicationType,
        /** Whether this is a first-party application. Third-party applications require an organization_id. */
        public bool $isFirstParty,
        /** A description for the application. */
        public ?string $description = null,
        /**
         * The OAuth scopes granted to the application.
         * @var array<string>|null
         */
        public ?array $scopes = null,
        /**
         * Redirect URIs for the application.
         * @var array<\WorkOS\Resource\RedirectUriInput>|null
         */
        public ?array $redirectUris = null,
        /** Whether the application uses PKCE (Proof Key for Code Exchange). */
        public ?bool $usesPkce = null,
        /** The organization ID this application belongs to. Required when is_first_party is false. */
        public ?string $organizationId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            applicationType: $data['application_type'],
            isFirstParty: $data['is_first_party'],
            description: $data['description'] ?? null,
            scopes: $data['scopes'] ?? null,
            redirectUris: isset($data['redirect_uris']) ? array_map(fn ($item) => RedirectUriInput::fromArray($item), $data['redirect_uris']) : null,
            usesPkce: $data['uses_pkce'] ?? null,
            organizationId: $data['organization_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'application_type' => $this->applicationType,
            'is_first_party' => $this->isFirstParty,
            'description' => $this->description,
            'scopes' => $this->scopes,
            'redirect_uris' => $this->redirectUris !== null ? array_map(fn ($item) => $item->toArray(), $this->redirectUris) : null,
            'uses_pkce' => $this->usesPkce,
            'organization_id' => $this->organizationId,
        ];
    }
}
