<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class CreateUserOrganizationMembership implements \JsonSerializable
{
    public function __construct(
        public string $userId,
        public string $organizationId,
        public ?string $roleSlug = null,
        public ?array $roleSlugs = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            userId: $data['user_id'],
            organizationId: $data['organization_id'],
            roleSlug: $data['role_slug'] ?? null,
            roleSlugs: $data['role_slugs'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'role_slug' => $this->roleSlug,
            'role_slugs' => $this->roleSlugs,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
