<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum CustomProviderDefinitionAuthenticateVia: string
{
    case RequestBody = 'request_body';
    case BasicAuthHeader = 'basic_auth_header';
}
