<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationsListResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Indicates this is a list response. */
        public string $object,
        /**
         * A list of [providers](https://workos.com/docs/reference/pipes/provider), each including a [`connected_account`](https://workos.com/docs/reference/pipes/connected-account) field with the user's connection status.
         * @var array<\WorkOS\Resource\DataIntegrationsListResponseData>
         */
        public array $data,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            data: array_map(fn ($item) => DataIntegrationsListResponseData::fromArray($item), $data['data']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'data' => array_map(fn ($item) => $item->toArray(), $this->data),
        ];
    }
}
