<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationsGetDataIntegrationAuthorizeUrlRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the user to authorize. */
        public string $userId,
        /** An organization ID to scope the authorization to a specific organization. */
        public ?string $organizationId = null,
        /** The URL to redirect the user to after authorization. */
        public ?string $returnTo = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            userId: $data['user_id'],
            organizationId: $data['organization_id'] ?? null,
            returnTo: $data['return_to'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'return_to' => $this->returnTo,
        ];
    }
}
