<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationsCreateApiKeyConnectionRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** A [User](https://workos.com/docs/reference/authkit/user) identifier. */
        public string $userId,
        /** The API key secret to store for this integration. */
        public string $secret,
        /** Must be `add`: this endpoint only creates another connection. The first connection for an owner shape fills the compatibility slot; later connections are standard. Creating an additional connection is not yet available: until it is, `add` succeeds only when the owner has no connection for this integration and otherwise returns 404 `multiple_connections_unavailable`. */
        public string $connectionIntent,
        /** An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. Required when `connection_owner` is `organization`. */
        public ?string $organizationId = null,
        /** Whose connection to create or rotate. `user` (the default) addresses the connection owned by `user_id`. `organization` addresses the connection shared by every member of `organization_id`; `user_id` then identifies the member performing the request and must be an active member of the organization. */
        public ?PipesOwnership $connectionOwner = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            userId: $data['user_id'],
            secret: $data['secret'],
            connectionIntent: $data['connection_intent'] ?? 'add',
            organizationId: $data['organization_id'] ?? null,
            connectionOwner: isset($data['connection_owner']) ? PipesOwnership::from($data['connection_owner']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'secret' => $this->secret,
            'connection_intent' => $this->connectionIntent,
            'organization_id' => $this->organizationId,
            'connection_owner' => $this->connectionOwner?->value,
        ];
    }
}
