<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationConfigurationListResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Indicates this is a list response. */
        public string $object,
        /**
         * A list of data integration configurations for the organization.
         * @var array<\WorkOS\Resource\DataIntegrationConfigurationResponse>
         */
        public array $data,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'list',
            data: array_map(fn ($item) => DataIntegrationConfigurationResponse::fromArray($item), $data['data']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'data' => array_map(fn ($item) => $item->toArray(), $this->data),
        ];
    }
}
