<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationsGetDataIntegrationAuthorizeUrlRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the user to authorize. When `connection_owner` is `organization`, this is the user authorizing on behalf of the organization; they must be an active member of the organization and do not become the owner of the resulting connected account. */
        public string $userId,
        /** An organization ID to scope the authorization to a specific organization. Required when `connection_owner` is `organization`. */
        public ?string $organizationId = null,
        /** Who will own the connected account. `user` (the default) connects the user's own account. `organization` connects the organization's shared account and requires `organization_id`. */
        public ?PipesOwnership $connectionOwner = null,
        /** The URL to redirect the user to after authorization. */
        public ?string $returnTo = null,
        /**
         * Connect-time config values for the provider-declared `installation`-scope fields (e.g. a Zendesk `subdomain`), keyed by the config field. Only fields the provider declares may be supplied, and required fields must be provided unless already pinned on the integration.
         * @var array<string, string>|null
         */
        public ?array $config = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            userId: $data['user_id'],
            organizationId: $data['organization_id'] ?? null,
            connectionOwner: isset($data['connection_owner']) ? PipesOwnership::from($data['connection_owner']) : null,
            returnTo: $data['return_to'] ?? null,
            config: $data['config'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'connection_owner' => $this->connectionOwner?->value,
            'return_to' => $this->returnTo,
            'config' => $this->config,
        ];
    }
}
