<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationCredentialsResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Indicates credentials are available. */
        public ?bool $active = null,
        /** The credential object containing the vended secret. */
        public ?DataIntegrationCredentialsResponseCredential $credential = null,
        /**
         * The reason credentials are unavailable. Additional values may be added in the future; handle unknown values gracefully.
         * - `"not_installed"`: The user does not have the integration installed.
         * - `"needs_reauthorization"`: The user needs to reauthorize the integration.
         */
        public ?DataIntegrationAccessTokenResponseError $error = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            active: $data['active'] ?? null,
            credential: isset($data['credential']) ? DataIntegrationCredentialsResponseCredential::fromArray($data['credential']) : null,
            error: isset($data['error']) ? DataIntegrationAccessTokenResponseError::from($data['error']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'active' => $this->active,
            'credential' => $this->credential?->toArray(),
            'error' => $this->error?->value,
        ];
    }
}
