<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum DataIntegrationState: string
{
    case Valid = 'valid';
    case Invalid = 'invalid';
    case Requested = 'requested';
}
