<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The credentials configured for the Data Integration. */
readonly class DataIntegrationCredential implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The credentials type. `custom` uses your own OAuth app credentials; `organization` has each organization supply its own credentials (so `client_id`/`redacted_client_secret` are null on the integration itself). */
        public DataIntegrationCredentialType $type,
        /** The OAuth client ID configured for the provider app. Null for `organization` credentials. */
        public ?string $clientId,
        /** The last four characters of the OAuth client secret. The full secret is never returned. Null for `organization` credentials. */
        public ?string $redactedClientSecret,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            type: DataIntegrationCredentialType::from($data['type']),
            clientId: $data['client_id'] ?? null,
            redactedClientSecret: $data['redacted_client_secret'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'type' => $this->type->value,
            'client_id' => $this->clientId,
            'redacted_client_secret' => $this->redactedClientSecret,
        ];
    }
}
