<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationsVendCredentialsRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** A [User](https://workos.com/docs/reference/authkit/user) identifier. */
        public string $userId,
        /** An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. */
        public ?string $organizationId = null,
        /** A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select a specific connection when the user has several for this provider. */
        public ?string $connectedAccountId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            userId: $data['user_id'],
            organizationId: $data['organization_id'] ?? null,
            connectedAccountId: $data['connected_account_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'connected_account_id' => $this->connectedAccountId,
        ];
    }
}
