<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DataIntegrationsUpsertApiKeyRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** A [User](https://workos.com/docs/reference/authkit/user) identifier. */
        public string $userId,
        /** The API key secret to store for this integration. */
        public string $secret,
        /** An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. */
        public ?string $organizationId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            userId: $data['user_id'],
            secret: $data['secret'],
            organizationId: $data['organization_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'secret' => $this->secret,
            'organization_id' => $this->organizationId,
        ];
    }
}
