<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum DataIntegrationAuthMethods: string
{
    case OAuth = 'oauth';
    case ApiKey = 'api_key';
}
