<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DeleteObjectResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Name of the deleted object. */
        public string $name,
        /** Whether the deletion succeeded. */
        public bool $success,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            success: $data['success'],
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'success' => $this->success,
        ];
    }
}
