<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DeleteGroupRoleAssignmentsByCriteria implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The slug of the role to remove assignments for. */
        public string $roleSlug,
        /** The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`. */
        public ?string $resourceId = null,
        /** The external ID of the resource. */
        public ?string $resourceExternalId = null,
        /** The resource type slug. */
        public ?string $resourceTypeSlug = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            roleSlug: $data['role_slug'],
            resourceId: $data['resource_id'] ?? null,
            resourceExternalId: $data['resource_external_id'] ?? null,
            resourceTypeSlug: $data['resource_type_slug'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'role_slug' => $this->roleSlug,
            'resource_id' => $this->resourceId,
            'resource_external_id' => $this->resourceExternalId,
            'resource_type_slug' => $this->resourceTypeSlug,
        ];
    }
}
