<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DirectoryMetadataUser implements \JsonSerializable
{
    public function __construct(
        public int $active,
        public int $inactive,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            active: $data['active'],
            inactive: $data['inactive'],
        );
    }

    public function toArray(): array
    {
        return [
            'active' => $this->active,
            'inactive' => $this->inactive,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
