<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DirectoryUserWithGroupsEmail implements \JsonSerializable
{
    public function __construct(
        public ?bool $primary = null,
        public ?string $type = null,
        public ?string $value = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            primary: $data['primary'] ?? null,
            type: $data['type'] ?? null,
            value: $data['value'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'primary' => $this->primary,
            'type' => $this->type,
            'value' => $this->value,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
