<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class DirectorySyncResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The sync request was queued for asynchronous processing. This does not indicate that the sync has started or completed. */
        public string $status,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            status: $data['status'] ?? 'queued',
        );
    }

    public function toArray(): array
    {
        return [
            'status' => $this->status,
        ];
    }
}
