<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Directory implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the Directory object. */
        public string $object,
        /** Unique identifier for the Directory. */
        public string $id,
        /** The unique identifier for the Organization in which the directory resides. */
        public string $organizationId,
        /** External Key for the Directory. */
        public string $externalKey,
        /** The type of external Directory Provider integrated with. */
        public DirectoryType $type,
        /** Describes whether the Directory has been successfully connected to an external provider. */
        public DirectoryState $state,
        /** The name of the directory. */
        public string $name,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
        /** The URL associated with an Enterprise Client. */
        public ?string $domain = null,
        /** Aggregate counts of directory users and groups synced from the provider. */
        public ?DirectoryMetadata $metadata = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'directory',
            id: $data['id'],
            organizationId: $data['organization_id'],
            externalKey: $data['external_key'],
            type: DirectoryType::from($data['type']),
            state: DirectoryState::from($data['state']),
            name: $data['name'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            domain: $data['domain'] ?? null,
            metadata: isset($data['metadata']) ? DirectoryMetadata::fromArray($data['metadata']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'organization_id' => $this->organizationId,
            'external_key' => $this->externalKey,
            'type' => $this->type->value,
            'state' => $this->state->value,
            'name' => $this->name,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'domain' => $this->domain,
            'metadata' => $this->metadata?->toArray(),
        ];
    }
}
