<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum DsyncDeletedDataState: string
{
    case Active = 'active';
    case Validating = 'validating';
    case InvalidCredentials = 'invalid_credentials';
    case Inactive = 'inactive';
    case Deleting = 'deleting';
}
