<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class EmailVerification implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the email verification object. */
        public string $object,
        /** The unique ID of the email verification code. */
        public string $id,
        /** The unique ID of the user. */
        public string $userId,
        /** The email address of the user. */
        public string $email,
        /** The timestamp when the email verification code expires. */
        public \DateTimeImmutable $expiresAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
        /** The code used to verify the email. */
        public string $code,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'email_verification',
            id: $data['id'],
            userId: $data['user_id'],
            email: $data['email'],
            expiresAt: new \DateTimeImmutable($data['expires_at']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            code: $data['code'],
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'user_id' => $this->userId,
            'email' => $this->email,
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'code' => $this->code,
        ];
    }
}
