<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class EmailChange implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public User $user,
        public string $newEmail,
        public \DateTimeImmutable $expiresAt,
        public \DateTimeImmutable $createdAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            user: User::fromArray($data['user']),
            newEmail: $data['new_email'],
            expiresAt: new \DateTimeImmutable($data['expires_at'] ?? 'now'),
            createdAt: new \DateTimeImmutable($data['created_at'] ?? 'now'),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'user' => $this->user->toArray(),
            'new_email' => $this->newEmail,
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
