<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class EmailVerificationCodeSessionAuthenticateRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The client ID of the application. */
        public string $clientId,
        /** The client secret of the application. */
        public string $clientSecret,
        public string $grantType,
        /** The email verification code. */
        public string $code,
        /** The pending authentication token from a previous authentication attempt. */
        public string $pendingAuthenticationToken,
        /** The IP address of the user's request. */
        public ?string $ipAddress = null,
        /** A unique identifier for the device. */
        public ?string $deviceId = null,
        /** The user agent string from the user's browser. */
        public ?string $userAgent = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            clientId: $data['client_id'],
            clientSecret: $data['client_secret'],
            grantType: $data['grant_type'] ?? 'urn:workos:oauth:grant-type:email-verification:code',
            code: $data['code'],
            pendingAuthenticationToken: $data['pending_authentication_token'],
            ipAddress: $data['ip_address'] ?? null,
            deviceId: $data['device_id'] ?? null,
            userAgent: $data['user_agent'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'grant_type' => $this->grantType,
            'code' => $this->code,
            'pending_authentication_token' => $this->pendingAuthenticationToken,
            'ip_address' => $this->ipAddress,
            'device_id' => $this->deviceId,
            'user_agent' => $this->userAgent,
        ];
    }
}
