<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The actor who performed the action. */
readonly class EventContextActor implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the actor. */
        public string $id,
        /** The source of the actor that performed the action. */
        public EventContextActorSource $source,
        /** The name of the actor. */
        public ?string $name,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            source: EventContextActorSource::from($data['source']),
            name: $data['name'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'source' => $this->source->value,
            'name' => $this->name,
        ];
    }
}
