<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Flag implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public string $id,
        public string $slug,
        public string $name,
        public ?string $description,
        public ?FlagOwner $owner,
        public array $tags,
        public bool $enabled,
        public bool $defaultValue,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            slug: $data['slug'],
            name: $data['name'],
            description: $data['description'],
            owner: FlagOwner::fromArray($data['owner']),
            tags: $data['tags'],
            enabled: $data['enabled'],
            defaultValue: $data['default_value'],
            createdAt: new \DateTimeImmutable($data['created_at'] ?? 'now'),
            updatedAt: new \DateTimeImmutable($data['updated_at'] ?? 'now'),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'slug' => $this->slug,
            'name' => $this->name,
            'description' => $this->description,
            'owner' => $this->owner?->toArray(),
            'tags' => $this->tags,
            'enabled' => $this->enabled,
            'default_value' => $this->defaultValue,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
