<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Flag implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the Feature Flag object. */
        public string $object,
        /** Unique identifier of the Feature Flag. */
        public string $id,
        /** A unique key to reference the Feature Flag. */
        public string $slug,
        /** A descriptive name for the Feature Flag. This field does not need to be unique. */
        public string $name,
        /** A description for the Feature Flag. */
        public ?string $description,
        /** The owner of the Feature Flag. */
        public ?FlagOwner $owner,
        /**
         * Labels assigned to the Feature Flag for categorizing and filtering.
         * @var array<string>
         */
        public array $tags,
        /** Specifies whether the Feature Flag is active for the current environment. */
        public bool $enabled,
        /** The value returned for users and organizations who don't match any configured targeting rules. */
        public bool $defaultValue,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'feature_flag',
            id: $data['id'],
            slug: $data['slug'],
            name: $data['name'],
            description: $data['description'] ?? null,
            owner: isset($data['owner']) ? FlagOwner::fromArray($data['owner']) : null,
            tags: $data['tags'],
            enabled: $data['enabled'],
            defaultValue: $data['default_value'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'slug' => $this->slug,
            'name' => $this->name,
            'description' => $this->description,
            'owner' => $this->owner?->toArray(),
            'tags' => $this->tags,
            'enabled' => $this->enabled,
            'default_value' => $this->defaultValue,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
