<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class FlagCreated implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier for the event. */
        public string $id,
        public string $event,
        /** The event payload. */
        public FlagCreatedData $data,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** Additional context about the event. */
        public FlagCreatedContext $context,
        /** Distinguishes the Event object. */
        public string $object,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            event: $data['event'],
            data: FlagCreatedData::fromArray($data['data']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            context: FlagCreatedContext::fromArray($data['context']),
            object: $data['object'],
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'event' => $this->event,
            'data' => $this->data->toArray(),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'context' => $this->context->toArray(),
            'object' => $this->object,
        ];
    }
}
