<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class FlagRuleUpdatedContextPreviousAttributeContextConfiguredTargetUser implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the user. */
        public string $id,
        /** The email of the user. */
        public string $email,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            email: $data['email'],
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
        ];
    }
}
