<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The previous context attributes of the flag rule. */
readonly class FlagRuleUpdatedContextPreviousAttributeContext implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The previous access type of the flag rule. */
        public ?FlagRuleUpdatedContextAccessType $accessType = null,
        /** The previous configured targets for the flag rule. */
        public ?FlagRuleUpdatedContextPreviousAttributeContextConfiguredTarget $configuredTargets = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            accessType: isset($data['access_type']) ? FlagRuleUpdatedContextAccessType::from($data['access_type']) : null,
            configuredTargets: isset($data['configured_targets']) ? FlagRuleUpdatedContextPreviousAttributeContextConfiguredTarget::fromArray($data['configured_targets']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'access_type' => $this->accessType instanceof \BackedEnum ? $this->accessType->value : $this->accessType,
            'configured_targets' => $this->configuredTargets?->toArray(),
        ];
    }
}
