<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class GenerateLink implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $organization,
        public ?string $returnUrl = null,
        public ?string $successUrl = null,
        public ?GenerateLinkIntent $intent = null,
        public ?IntentOptions $intentOptions = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            organization: $data['organization'],
            returnUrl: $data['return_url'] ?? null,
            successUrl: $data['success_url'] ?? null,
            intent: isset($data['intent']) ? GenerateLinkIntent::from($data['intent']) : null,
            intentOptions: isset($data['intent_options']) ? IntentOptions::fromArray($data['intent_options']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'organization' => $this->organization,
            'return_url' => $this->returnUrl,
            'success_url' => $this->successUrl,
            'intent' => $this->intent instanceof \BackedEnum ? $this->intent->value : $this->intent,
            'intent_options' => $this->intentOptions?->toArray(),
        ];
    }
}
