<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class GroupRoleAssignmentList implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Indicates this is a list response. */
        public string $object,
        /**
         * The list of records for the current page.
         * @var array<\WorkOS\Resource\GroupRoleAssignment>
         */
        public array $data,
        public ListMetadata $listMetadata,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'list',
            data: array_map(fn ($item) => GroupRoleAssignment::fromArray($item), $data['data']),
            listMetadata: ListMetadata::fromArray($data['list_metadata']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'data' => array_map(fn ($item) => $item->toArray(), $this->data),
            'list_metadata' => $this->listMetadata->toArray(),
        ];
    }
}
