<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class IntentOptions implements \JsonSerializable
{
    public function __construct(
        public SSOIntentOptions $sso,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            sso: SSOIntentOptions::fromArray($data['sso']),
        );
    }

    public function toArray(): array
    {
        return [
            'sso' => $this->sso->toArray(),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
