<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** Pagination cursors for navigating between pages of results. */
readonly class ItContactListListMetadata implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** An object ID that defines your place in the list. When the ID is not present, you are at the start of the list. */
        public ?string $before,
        /** An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. */
        public ?string $after,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            before: $data['before'] ?? null,
            after: $data['after'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'before' => $this->before,
            'after' => $this->after,
        ];
    }
}
