<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ListModel implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public array $data,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            data: array_map(fn ($item) => ListData::fromArray($item), $data['data']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'data' => array_map(fn ($item) => $item->toArray(), $this->data),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
