<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** A static snapshot of an encrypted object. */
readonly class ObjectVersion implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Timestamp when the version was created. */
        public \DateTimeImmutable $createdAt,
        /** Whether this is the active version. */
        public bool $currentVersion,
        /** Hash of the object value. */
        public string $etag,
        /** Unique identifier of the version. */
        public string $id,
        /** Number of bytes of stored data. */
        public int $size,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            createdAt: new \DateTimeImmutable($data['created_at']),
            currentVersion: $data['current_version'],
            etag: $data['etag'],
            id: $data['id'],
            size: $data['size'],
        );
    }

    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'current_version' => $this->currentVersion,
            'etag' => $this->etag,
            'id' => $this->id,
            'size' => $this->size,
        ];
    }
}
