<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** Additional context about the event. */
readonly class OrganizationDomainVerificationFailedContext implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The Google Analytics client ID. */
        public ?string $googleAnalyticsClientId = null,
        /** The Google Analytics sessions associated with the event. */
        public ?array $googleAnalyticsSessions = null,
        /** The anonymous ID from analytics. */
        public ?string $ajsAnonymousId = null,
        /** The client ID associated with the event. */
        public ?string $clientId = null,
        /** The actor who performed the action. */
        public ?OrganizationDomainVerificationFailedContextActor $actor = null,
        /** Attributes that changed from their previous values. */
        public ?array $previousAttributes = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            googleAnalyticsClientId: $data['google_analytics_client_id'] ?? null,
            googleAnalyticsSessions: $data['google_analytics_sessions'] ?? null,
            ajsAnonymousId: $data['ajs_anonymous_id'] ?? null,
            clientId: $data['client_id'] ?? null,
            actor: isset($data['actor']) ? OrganizationDomainVerificationFailedContextActor::fromArray($data['actor']) : null,
            previousAttributes: $data['previous_attributes'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'google_analytics_client_id' => $this->googleAnalyticsClientId,
            'google_analytics_sessions' => array_map(fn ($item) => $item->toArray(), $this->googleAnalyticsSessions ?? []),
            'ajs_anonymous_id' => $this->ajsAnonymousId,
            'client_id' => $this->clientId,
            'actor' => $this->actor?->toArray(),
            'previous_attributes' => $this->previousAttributes,
        ];
    }
}
