<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Organization implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the Organization object. */
        public string $object,
        /** Unique identifier of the Organization. */
        public string $id,
        /** A descriptive name for the Organization. This field does not need to be unique. */
        public string $name,
        /**
         * List of Organization Domains.
         * @var array<\WorkOS\Resource\OrganizationDomain>
         */
        public array $domains,
        /**
         * Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization.
         * @var array<string, string>
         */
        public array $metadata,
        /** The external ID of the Organization. */
        public ?string $externalId,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
        /** The Stripe customer ID of the Organization. */
        public ?string $stripeCustomerId = null,
        /**
         * Whether the Organization allows profiles outside of its managed domains.
         * @deprecated
         */
        public ?bool $allowProfilesOutsideOrganization = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'organization',
            id: $data['id'],
            name: $data['name'],
            domains: array_map(fn ($item) => OrganizationDomain::fromArray($item), $data['domains']),
            metadata: $data['metadata'],
            externalId: $data['external_id'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            stripeCustomerId: $data['stripe_customer_id'] ?? null,
            allowProfilesOutsideOrganization: $data['allow_profiles_outside_organization'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'name' => $this->name,
            'domains' => array_map(fn ($item) => $item->toArray(), $this->domains),
            'metadata' => $this->metadata,
            'external_id' => $this->externalId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'stripe_customer_id' => $this->stripeCustomerId,
            'allow_profiles_outside_organization' => $this->allowProfilesOutsideOrganization,
        ];
    }
}
