<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Organization implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $object,
        public string $id,
        public string $name,
        public array $domains,
        public array $metadata,
        public ?string $externalId,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        public ?string $stripeCustomerId = null,
        public ?bool $allowProfilesOutsideOrganization = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            name: $data['name'],
            domains: array_map(fn ($item) => OrganizationDomain::fromArray($item), $data['domains']),
            metadata: $data['metadata'],
            externalId: $data['external_id'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            stripeCustomerId: $data['stripe_customer_id'] ?? null,
            allowProfilesOutsideOrganization: $data['allow_profiles_outside_organization'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'name' => $this->name,
            'domains' => array_map(fn ($item) => $item->toArray(), $this->domains),
            'metadata' => $this->metadata,
            'external_id' => $this->externalId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'stripe_customer_id' => $this->stripeCustomerId,
            'allow_profiles_outside_organization' => $this->allowProfilesOutsideOrganization,
        ];
    }
}
