<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class OrganizationDomainData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The domain value. */
        public string $domain,
        /** The verification state of the domain. */
        public OrganizationDomainDataState $state,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            domain: $data['domain'],
            state: OrganizationDomainDataState::from($data['state']),
        );
    }

    public function toArray(): array
    {
        return [
            'domain' => $this->domain,
            'state' => $this->state->value,
        ];
    }
}
