<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class OrganizationDomainData implements \JsonSerializable
{
    public function __construct(
        public string $domain,
        public OrganizationDomainDataState $state,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            domain: $data['domain'],
            state: OrganizationDomainDataState::tryFrom($data['state']) ?? $data['state'],
        );
    }

    public function toArray(): array
    {
        return [
            'domain' => $this->domain,
            'state' => $this->state->value,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
