<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class PasswordReset implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $object,
        public string $id,
        public string $userId,
        public string $email,
        public \DateTimeImmutable $expiresAt,
        public \DateTimeImmutable $createdAt,
        public string $passwordResetToken,
        public string $passwordResetUrl,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            userId: $data['user_id'],
            email: $data['email'],
            expiresAt: new \DateTimeImmutable($data['expires_at']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            passwordResetToken: $data['password_reset_token'],
            passwordResetUrl: $data['password_reset_url'],
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'user_id' => $this->userId,
            'email' => $this->email,
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'password_reset_token' => $this->passwordResetToken,
            'password_reset_url' => $this->passwordResetUrl,
        ];
    }
}
