<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum PatchConnectionOIDCOptionsTokenAuthenticationMethod: string
{
    case ClientSecretPost = 'client_secret_post';
    case ClientSecretBasic = 'client_secret_basic';
    case PrivateKeyJWT = 'private_key_jwt';
}
