<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class Permission implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $object,
        public string $id,
        public string $slug,
        public string $name,
        public ?string $description,
        public bool $system,
        public string $resourceTypeSlug,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            slug: $data['slug'],
            name: $data['name'],
            description: $data['description'] ?? null,
            system: $data['system'],
            resourceTypeSlug: $data['resource_type_slug'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'slug' => $this->slug,
            'name' => $this->name,
            'description' => $this->description,
            'system' => $this->system,
            'resource_type_slug' => $this->resourceTypeSlug,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
