<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class PipeConnectedAccount implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The connected account object. */
        public string $object,
        /** The unique ID of the connected account. */
        public string $id,
        /** The unique ID of the data integration. */
        public string $dataIntegrationId,
        /** The provider slug for this connected account. */
        public string $providerSlug,
        /** The ID of the User the connected account belongs to. */
        public ?string $userId,
        /** The ID of the Organization the connected account belongs to. */
        public ?string $organizationId,
        /**
         * The OAuth scopes granted for this connected account.
         * @var array<string>
         */
        public array $scopes,
        /** The state of the connected account. */
        public PipeConnectedAccountState $state,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $updatedAt,
        /** Whether this is the compatibility connection visible to undeclared clients or a standard connection for plural-aware clients. Historical events may omit this field. */
        public ?ConnectedAccountConnectionRole $connectionRole = null,
        /** A best-effort identifier for the provider account this connection points at. It is not the connection identifier or a selector. Historical events may omit this field. */
        public ?string $accountIdentifier = null,
        /** A mutable, non-unique display name for the provider account connection. Historical events may omit this field. */
        public ?string $accountDisplayName = null,
        /** How the connection authenticates. Historical events may omit this field. */
        public ?DataIntegrationAuthMethods $authMethod = null,
        /** The last four characters of the API key, or null for other authentication methods. Historical events may omit this field. */
        public ?string $apiKeyLast4 = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'connected_account',
            id: $data['id'],
            dataIntegrationId: $data['data_integration_id'],
            providerSlug: $data['provider_slug'],
            userId: $data['user_id'] ?? null,
            organizationId: $data['organization_id'] ?? null,
            scopes: $data['scopes'],
            state: PipeConnectedAccountState::from($data['state']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            connectionRole: isset($data['connection_role']) ? ConnectedAccountConnectionRole::from($data['connection_role']) : null,
            accountIdentifier: $data['account_identifier'] ?? null,
            accountDisplayName: $data['account_display_name'] ?? null,
            authMethod: isset($data['auth_method']) ? DataIntegrationAuthMethods::from($data['auth_method']) : null,
            apiKeyLast4: $data['api_key_last_4'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'data_integration_id' => $this->dataIntegrationId,
            'provider_slug' => $this->providerSlug,
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'scopes' => $this->scopes,
            'state' => $this->state->value,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'connection_role' => $this->connectionRole?->value,
            'account_identifier' => $this->accountIdentifier,
            'account_display_name' => $this->accountDisplayName,
            'auth_method' => $this->authMethod?->value,
            'api_key_last_4' => $this->apiKeyLast4,
        ];
    }
}
