<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class RadarStandaloneAssessRequest implements \JsonSerializable
{
    public function __construct(
        public string $ipAddress,
        public string $userAgent,
        public string $email,
        public RadarStandaloneAssessRequestAuthMethod $authMethod,
        public RadarStandaloneAssessRequestAction $action,
        public ?string $deviceFingerprint = null,
        public ?string $botScore = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            ipAddress: $data['ip_address'],
            userAgent: $data['user_agent'],
            email: $data['email'],
            authMethod: RadarStandaloneAssessRequestAuthMethod::tryFrom($data['auth_method']) ?? $data['auth_method'],
            action: RadarStandaloneAssessRequestAction::tryFrom($data['action']) ?? $data['action'],
            deviceFingerprint: $data['device_fingerprint'] ?? null,
            botScore: $data['bot_score'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'ip_address' => $this->ipAddress,
            'user_agent' => $this->userAgent,
            'email' => $this->email,
            'auth_method' => $this->authMethod->value,
            'action' => $this->action->value,
            'device_fingerprint' => $this->deviceFingerprint,
            'bot_score' => $this->botScore,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
