<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class RadarStandaloneDeleteRadarListEntryRequest implements \JsonSerializable
{
    public function __construct(
        public string $entry,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            entry: $data['entry'],
        );
    }

    public function toArray(): array
    {
        return [
            'entry' => $this->entry,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
