<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class RekeyRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Map of values used to determine the new encryption key.
         * @var array<string, string>
         */
        public array $context,
        /** Base64-encoded encrypted data key blob to re-encrypt. */
        public string $encryptedKeys,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            context: $data['context'],
            encryptedKeys: $data['encrypted_keys'],
        );
    }

    public function toArray(): array
    {
        return [
            'context' => $this->context,
            'encrypted_keys' => $this->encryptedKeys,
        ];
    }
}
