<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ResendUserInviteOptions implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?ResendUserInviteOptionsLocale $locale = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            locale: isset($data['locale']) ? ResendUserInviteOptionsLocale::from($data['locale']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'locale' => $this->locale instanceof \BackedEnum ? $this->locale->value : $this->locale,
        ];
    }
}
