<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class ResetPasswordResponse implements \JsonSerializable
{
    public function __construct(
        public User $user,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            user: User::fromArray($data['user']),
        );
    }

    public function toArray(): array
    {
        return [
            'user' => $this->user->toArray(),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
