<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The event payload. */
readonly class ResourceExportDownloadedData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the resource export. */
        public string $id,
        /** The type of resource being exported. */
        public ResourceExportFailedDataResourceType $resourceType,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            resourceType: ResourceExportFailedDataResourceType::from($data['resource_type']),
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'resource_type' => $this->resourceType->value,
        ];
    }
}
