<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The resource to which the role is assigned. */
readonly class RoleAssignmentResource implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The unique ID of the Resource. */
        public string $id,
        /** An identifier you provide to reference the resource in your system. */
        public string $externalId,
        /** The slug of the resource type this resource belongs to. */
        public string $resourceTypeSlug,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            externalId: $data['external_id'],
            resourceTypeSlug: $data['resource_type_slug'],
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'external_id' => $this->externalId,
            'resource_type_slug' => $this->resourceTypeSlug,
        ];
    }
}
