<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class RoleAssignment implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public string $id,
        public SlimRole $role,
        public RoleAssignmentResource $resource,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            role: SlimRole::fromArray($data['role']),
            resource: RoleAssignmentResource::fromArray($data['resource']),
            createdAt: new \DateTimeImmutable($data['created_at'] ?? 'now'),
            updatedAt: new \DateTimeImmutable($data['updated_at'] ?? 'now'),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'role' => $this->role->toArray(),
            'resource' => $this->resource->toArray(),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
