<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class RoleAssignmentResource implements \JsonSerializable
{
    public function __construct(
        public string $id,
        public string $externalId,
        public string $resourceTypeSlug,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            externalId: $data['external_id'],
            resourceTypeSlug: $data['resource_type_slug'],
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'external_id' => $this->externalId,
            'resource_type_slug' => $this->resourceTypeSlug,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
