<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class SAMLSpSigningCertificate implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Distinguishes the SAML Service Provider signing certificate object. */
        public string $object,
        /** Unique identifier for the Service Provider signing key pair. WorkOS holds the corresponding private key, which is never exposed. */
        public string $id,
        /** The PEM-encoded public X.509 certificate. */
        public string $value,
        /** When the certificate becomes valid. */
        public ?\DateTimeImmutable $notBefore,
        /** When the certificate expires. */
        public ?\DateTimeImmutable $notAfter,
        /** An ISO 8601 timestamp. */
        public \DateTimeImmutable $createdAt,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? 'saml_sp_signing_certificate',
            id: $data['id'],
            value: $data['value'],
            notBefore: isset($data['not_before']) ? new \DateTimeImmutable($data['not_before']) : null,
            notAfter: isset($data['not_after']) ? new \DateTimeImmutable($data['not_after']) : null,
            createdAt: new \DateTimeImmutable($data['created_at']),
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'value' => $this->value,
            'not_before' => $this->notBefore?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'not_after' => $this->notAfter?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
