<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class SendRadarSmsChallengeResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the SMS verification. Pass this to the authenticate endpoint to verify the code. */
        public string $verificationId,
        /** The phone number the verification code was sent to. */
        public string $phoneNumber,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            verificationId: $data['verification_id'],
            phoneNumber: $data['phone_number'],
        );
    }

    public function toArray(): array
    {
        return [
            'verification_id' => $this->verificationId,
            'phone_number' => $this->phoneNumber,
        ];
    }
}
