<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum SSOGrantType: string
{
    case AuthorizationCode = 'authorization_code';
    case UrnIetfParamsOAuthGrantTypeTokenExchange = 'urn:ietf:params:oauth:grant-type:token-exchange';
}
