<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class SSOIntentOptions implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $bookmarkSlug = null,
        public ?string $providerType = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            bookmarkSlug: $data['bookmark_slug'] ?? null,
            providerType: $data['provider_type'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'bookmark_slug' => $this->bookmarkSlug,
            'provider_type' => $this->providerType,
        ];
    }
}
