<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class SSOLogoutAuthorizeRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $profileId,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            profileId: $data['profile_id'],
        );
    }

    public function toArray(): array
    {
        return [
            'profile_id' => $this->profileId,
        ];
    }
}
