<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class SSOLogoutAuthorizeResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The URL to redirect the user to in order to log out ([Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint ready to use). */
        public string $logoutUrl,
        /** The logout token to be used in the [Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint. */
        public string $logoutToken,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            logoutUrl: $data['logout_url'],
            logoutToken: $data['logout_token'],
        );
    }

    public function toArray(): array
    {
        return [
            'logout_url' => $this->logoutUrl,
            'logout_token' => $this->logoutToken,
        ];
    }
}
