<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** OAuth tokens issued by the identity provider, if available. */
readonly class SSOTokenResponseOAuthToken implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The OAuth provider used for authentication. */
        public string $provider,
        /** The refresh token from the OAuth provider. */
        public string $refreshToken,
        /** The access token from the OAuth provider. */
        public string $accessToken,
        /** The timestamp at which the access token expires. */
        public int $expiresAt,
        /**
         * A list of OAuth scopes for which the access token is authorized.
         * @var array<string>
         */
        public array $scopes,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            provider: $data['provider'],
            refreshToken: $data['refresh_token'],
            accessToken: $data['access_token'],
            expiresAt: $data['expires_at'],
            scopes: $data['scopes'],
        );
    }

    public function toArray(): array
    {
        return [
            'provider' => $this->provider,
            'refresh_token' => $this->refreshToken,
            'access_token' => $this->accessToken,
            'expires_at' => $this->expiresAt,
            'scopes' => $this->scopes,
        ];
    }
}
