<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UpdateOAuthApplication implements \JsonSerializable
{
    public function __construct(
        public ?string $name = null,
        public ?string $description = null,
        public ?array $scopes = null,
        public ?array $redirectUris = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'] ?? null,
            description: $data['description'] ?? null,
            scopes: $data['scopes'] ?? null,
            redirectUris: $data['redirect_uris'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'description' => $this->description,
            'scopes' => $this->scopes,
            'redirect_uris' => array_map(fn ($item) => $item->toArray(), $this->redirectUris ?? []),
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
