<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum UpdateAuditLogsRetentionRetentionPeriod: string
{
    case Value1Month = '1_MONTH';
    case Value2Months = '2_MONTHS';
    case Value3Months = '3_MONTHS';
    case Value4Months = '4_MONTHS';
    case Value5Months = '5_MONTHS';
    case Value6Months = '6_MONTHS';
    case Value7Months = '7_MONTHS';
    case Value8Months = '8_MONTHS';
    case Value9Months = '9_MONTHS';
    case Value10Months = '10_MONTHS';
    case Value11Months = '11_MONTHS';
    case Value1Year = '1_YEAR';
    case Value2Years = '2_YEARS';
    case Value3Years = '3_YEARS';
    case Value4Years = '4_YEARS';
    case Value5Years = '5_YEARS';
    case Value6Years = '6_YEARS';
    case Value7Years = '7_YEARS';
    case Value8Years = '8_YEARS';
    case Value9Years = '9_YEARS';
    case Value10Years = '10_YEARS';
}
