<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UpdateDataIntegration implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** An optional description of the Data Integration. */
        public ?string $description = null,
        /** Whether the Data Integration is enabled. */
        public ?bool $enabled = null,
        /**
         * The OAuth scopes to request for the Data Integration. Pass `null` to reset to the provider's configured scopes.
         * @var array<string>|null
         */
        public ?array $scopes = null,
        /** New credentials for the Data Integration. When provided, rotates the stored client secret. */
        public ?DataIntegrationCredentialsDto $credentials = null,
        /** Updates to a custom provider's OAuth definition. Only valid for custom-provider integrations. */
        public ?UpdateCustomProviderDefinition $customProvider = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            description: $data['description'] ?? null,
            enabled: $data['enabled'] ?? null,
            scopes: $data['scopes'] ?? null,
            credentials: isset($data['credentials']) ? DataIntegrationCredentialsDto::fromArray($data['credentials']) : null,
            customProvider: isset($data['custom_provider']) ? UpdateCustomProviderDefinition::fromArray($data['custom_provider']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'description' => $this->description,
            'enabled' => $this->enabled,
            'scopes' => $this->scopes,
            'credentials' => $this->credentials?->toArray(),
            'custom_provider' => $this->customProvider?->toArray(),
        ];
    }
}
