<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UpdateAuditLogsRetention implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The number of days Audit Log events will be retained. Valid values are `30` and `365`. */
        public int $retentionPeriodInDays,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            retentionPeriodInDays: $data['retention_period_in_days'],
        );
    }

    public function toArray(): array
    {
        return [
            'retention_period_in_days' => $this->retentionPeriodInDays,
        ];
    }
}
