<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UpdateOAuthApplication implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The name of the application. */
        public ?string $name = null,
        /** A description for the application. */
        public ?string $description = null,
        /** The OAuth scopes granted to the application. */
        public ?array $scopes = null,
        /** Updated redirect URIs for the application. OAuth applications only. */
        public ?array $redirectUris = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'] ?? null,
            description: $data['description'] ?? null,
            scopes: $data['scopes'] ?? null,
            redirectUris: $data['redirect_uris'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'description' => $this->description,
            'scopes' => $this->scopes,
            'redirect_uris' => $this->redirectUris !== null ? array_map(fn ($item) => $item->toArray(), $this->redirectUris) : null,
        ];
    }
}
