<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UpdateUser implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The email address of the user. */
        public ?string $email = null,
        /** The first name of the user. */
        public ?string $firstName = null,
        /** The last name of the user. */
        public ?string $lastName = null,
        /** The user's full name. */
        public ?string $name = null,
        /** Whether the user's email has been verified. */
        public ?bool $emailVerified = null,
        /**
         * Object containing metadata key/value pairs associated with the user.
         * @var array<string, string>|null
         */
        public ?array $metadata = null,
        /** The external ID of the user. */
        public ?string $externalId = null,
        /** The user's preferred locale. */
        public ?string $locale = null,
        /** The password to set for the user. Mutually exclusive with `password_hash`, `password_hash_type`, and `password_salt_position`. */
        public ?string $password = null,
        /** The hashed password to set for the user. Required with `password_hash_type`. Mutually exclusive with `password`. */
        public ?string $passwordHash = null,
        /** The algorithm originally used to hash the password, used when providing a `password_hash`. Required with `password_hash`. Mutually exclusive with `password`. */
        public ?CreateUserPasswordHashType $passwordHashType = null,
        /** The position of the salt relative to the password when the `password_hash` digest was computed: `prefix` for `hash(salt + password)` or `suffix` for `hash(password + salt)`. Only supported with the `ssha256` hash type and only valid when a `password_hash` is provided. Defaults to `suffix`. Mutually exclusive with `password`. */
        public ?CreateUserPasswordSaltPosition $passwordSaltPosition = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            email: $data['email'] ?? null,
            firstName: $data['first_name'] ?? null,
            lastName: $data['last_name'] ?? null,
            name: $data['name'] ?? null,
            emailVerified: $data['email_verified'] ?? null,
            metadata: $data['metadata'] ?? null,
            externalId: $data['external_id'] ?? null,
            locale: $data['locale'] ?? null,
            password: $data['password'] ?? null,
            passwordHash: $data['password_hash'] ?? null,
            passwordHashType: isset($data['password_hash_type']) ? CreateUserPasswordHashType::from($data['password_hash_type']) : null,
            passwordSaltPosition: isset($data['password_salt_position']) ? CreateUserPasswordSaltPosition::from($data['password_salt_position']) : null,
        );
    }

    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'name' => $this->name,
            'email_verified' => $this->emailVerified,
            'metadata' => $this->metadata,
            'external_id' => $this->externalId,
            'locale' => $this->locale,
            'password' => $this->password,
            'password_hash' => $this->passwordHash,
            'password_hash_type' => $this->passwordHashType?->value,
            'password_salt_position' => $this->passwordSaltPosition?->value,
        ];
    }
}
