<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UpdateWebhookEndpoint implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $endpointUrl = null,
        public ?UpdateWebhookEndpointStatus $status = null,
        public ?array $events = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            endpointUrl: $data['endpoint_url'] ?? null,
            status: isset($data['status']) ? UpdateWebhookEndpointStatus::from($data['status']) : null,
            events: $data['events'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'endpoint_url' => $this->endpointUrl,
            'status' => $this->status instanceof \BackedEnum ? $this->status->value : $this->status,
            'events' => $this->events,
        ];
    }
}
