<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UrnWorkOSOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequest implements \JsonSerializable
{
    public function __construct(
        public string $clientId,
        public string $clientSecret,
        public string $grantType,
        public string $code,
        public string $email,
        public ?string $invitationToken = null,
        public ?string $ipAddress = null,
        public ?string $deviceId = null,
        public ?string $userAgent = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            clientId: $data['client_id'],
            clientSecret: $data['client_secret'],
            grantType: $data['grant_type'],
            code: $data['code'],
            email: $data['email'],
            invitationToken: $data['invitation_token'] ?? null,
            ipAddress: $data['ip_address'] ?? null,
            deviceId: $data['device_id'] ?? null,
            userAgent: $data['user_agent'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'grant_type' => $this->grantType,
            'code' => $this->code,
            'email' => $this->email,
            'invitation_token' => $this->invitationToken,
            'ip_address' => $this->ipAddress,
            'device_id' => $this->deviceId,
            'user_agent' => $this->userAgent,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
