<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UserIdentitiesGetItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The unique ID of the user in the external identity provider. */
        public string $idpId,
        /** The type of the identity. */
        public string $type,
        /** The type of OAuth provider for the identity. */
        public UserIdentitiesGetItemProvider $provider,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            idpId: $data['idp_id'],
            type: $data['type'],
            provider: UserIdentitiesGetItemProvider::from($data['provider']),
        );
    }

    public function toArray(): array
    {
        return [
            'idp_id' => $this->idpId,
            'type' => $this->type,
            'provider' => $this->provider->value,
        ];
    }
}
