<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum UserIdentitiesGetItemProvider: string
{
    case AppleOAuth = 'AppleOAuth';
    case BitbucketOAuth = 'BitbucketOAuth';
    case DiscordOAuth = 'DiscordOAuth';
    case GithubOAuth = 'GithubOAuth';
    case GitLabOAuth = 'GitLabOAuth';
    case GoogleOAuth = 'GoogleOAuth';
    case IntuitOAuth = 'IntuitOAuth';
    case LinkedInOAuth = 'LinkedInOAuth';
    case MicrosoftOAuth = 'MicrosoftOAuth';
    case SalesforceOAuth = 'SalesforceOAuth';
    case SlackOAuth = 'SlackOAuth';
    case VercelMarketplaceOAuth = 'VercelMarketplaceOAuth';
    case VercelOAuth = 'VercelOAuth';
    case XeroOAuth = 'XeroOAuth';
}
