<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UserInvite implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public string $id,
        public string $email,
        public UserInviteState $state,
        public ?\DateTimeImmutable $acceptedAt,
        public ?\DateTimeImmutable $revokedAt,
        public \DateTimeImmutable $expiresAt,
        public ?string $organizationId,
        public ?string $inviterUserId,
        public ?string $acceptedUserId,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        public string $token,
        public string $acceptInvitationUrl,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'],
            id: $data['id'],
            email: $data['email'],
            state: UserInviteState::tryFrom($data['state']) ?? $data['state'],
            acceptedAt: new \DateTimeImmutable($data['accepted_at'] ?? 'now'),
            revokedAt: new \DateTimeImmutable($data['revoked_at'] ?? 'now'),
            expiresAt: new \DateTimeImmutable($data['expires_at'] ?? 'now'),
            organizationId: $data['organization_id'],
            inviterUserId: $data['inviter_user_id'],
            acceptedUserId: $data['accepted_user_id'],
            createdAt: new \DateTimeImmutable($data['created_at'] ?? 'now'),
            updatedAt: new \DateTimeImmutable($data['updated_at'] ?? 'now'),
            token: $data['token'],
            acceptInvitationUrl: $data['accept_invitation_url'],
        );
    }

    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'id' => $this->id,
            'email' => $this->email,
            'state' => $this->state->value,
            'accepted_at' => $this->acceptedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'revoked_at' => $this->revokedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'organization_id' => $this->organizationId,
            'inviter_user_id' => $this->inviterUserId,
            'accepted_user_id' => $this->acceptedUserId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'token' => $this->token,
            'accept_invitation_url' => $this->acceptInvitationUrl,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
