<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UserConsentOptionChoice implements \JsonSerializable
{
    public function __construct(
        public ?string $value = null,
        public ?string $label = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            value: $data['value'] ?? null,
            label: $data['label'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'value' => $this->value,
            'label' => $this->label,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
