<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum UserManagementOrganizationMembershipStatuses: string
{
    case Active = 'active';
    case Inactive = 'inactive';
    case Pending = 'pending';
}
