<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UserCreateResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the Radar authentication attempt created for this request when Radar is enabled. Pass this value to the authenticate endpoint to associate the subsequent authentication with this Radar attempt. */
        public ?string $radarAuthAttemptId = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            radarAuthAttemptId: $data['radar_auth_attempt_id'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'radar_auth_attempt_id' => $this->radarAuthAttemptId,
        ];
    }
}
