<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class UserIdentitiesGetItem implements \JsonSerializable
{
    public function __construct(
        public string $idpId,
        public string $type,
        public UserIdentitiesGetItemProvider $provider,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            idpId: $data['idp_id'],
            type: $data['type'],
            provider: UserIdentitiesGetItemProvider::tryFrom($data['provider']) ?? $data['provider'],
        );
    }

    public function toArray(): array
    {
        return [
            'idp_id' => $this->idpId,
            'type' => $this->type,
            'provider' => $this->provider->value,
        ];
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
