<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

/** The event payload. */
readonly class VaultDataReadData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The unique identifier of the actor. */
        public string $actorId,
        public VaultDekReadDataActorSource $actorSource,
        /** The name of the actor. */
        public string $actorName,
        /** The name of the key-value store. */
        public string $kvName,
        /** The unique identifier of the encryption key. */
        public string $keyId,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            actorId: $data['actor_id'],
            actorSource: VaultDekReadDataActorSource::from($data['actor_source']),
            actorName: $data['actor_name'],
            kvName: $data['kv_name'],
            keyId: $data['key_id'],
        );
    }

    public function toArray(): array
    {
        return [
            'actor_id' => $this->actorId,
            'actor_source' => $this->actorSource->value,
            'actor_name' => $this->actorName,
            'kv_name' => $this->kvName,
            'key_id' => $this->keyId,
        ];
    }
}
