<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

readonly class WidgetSessionToken implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The ID of the organization to scope the widget session to. */
        public string $organizationId,
        /** The ID of the user to issue the widget session token for. */
        public ?string $userId = null,
        /** The scopes to grant the widget session. */
        public ?array $scopes = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            organizationId: $data['organization_id'],
            userId: $data['user_id'] ?? null,
            scopes: $data['scopes'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'user_id' => $this->userId,
            'scopes' => $this->scopes,
        ];
    }
}
