<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Resource;

enum WidgetSessionTokenScopes: string
{
    case WidgetsUsersTableManage = 'widgets:users-table:manage';
    case WidgetsDomainVerificationManage = 'widgets:domain-verification:manage';
    case WidgetsSSOManage = 'widgets:sso:manage';
    case WidgetsApiKeysManage = 'widgets:api-keys:manage';
    case WidgetsDsyncManage = 'widgets:dsync:manage';
    case WidgetsAuditLogStreamingManage = 'widgets:audit-log-streaming:manage';
}
