<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests;

use PHPUnit\Framework\TestCase;
use WorkOS\WorkOS;

class ClientTest extends TestCase
{
    public function testConstructor(): void
    {
        $client = new WorkOS(apiKey: 'test-key');
        $this->assertNotNull($client);
    }
}
