<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use WorkOS\TestHelper;

class ApiKeysTest extends TestCase
{
    use TestHelper;

    public function testCreateValidation(): void
    {
        $fixture = $this->loadFixture('api_key_validation_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->apiKeys()->createValidation(value: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\ApiKeyValidationResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('api_keys/validations', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['value']);
    }

    public function testDeleteApiKey(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->apiKeys()->deleteApiKey('test_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('api_keys/test_id', $request->getUri()->getPath());
    }

    public function testListOrganizationApiKeys(): void
    {
        $fixture = $this->loadFixture('list_api_key');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->apiKeys()->listOrganizationApiKeys('test_organizationId', before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal);
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('organizations/test_organizationId/api_keys', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
    }

    public function testCreateOrganizationApiKey(): void
    {
        $fixture = $this->loadFixture('api_key_with_value');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->apiKeys()->createOrganizationApiKey('test_organizationId', name: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\ApiKeyWithValue::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['name'], $result->name);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('organizations/test_organizationId/api_keys', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['name']);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_api_key');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->apiKeys()->listOrganizationApiKeys('test_organizationId');
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
