<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use WorkOS\TestHelper;

class ClientApiTest extends TestCase
{
    use TestHelper;

    public function testCreateToken(): void
    {
        $fixture = $this->loadFixture('client_api_token_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->clientApi()->createToken(organizationId: 'test_value', userId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\ClientApiTokenResponse::class, $result);
        $this->assertSame($fixture['token'], $result->token);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('client/token', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['organization_id']);
        $this->assertSame('test_value', $body['user_id']);
    }
}
