<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use WorkOS\TestHelper;

class MultiFactorAuthTest extends TestCase
{
    use TestHelper;

    public function testVerifyChallenge(): void
    {
        $fixture = $this->loadFixture('authentication_challenge_verify_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->verifyChallenge('test_id', code: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticationChallengeVerifyResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('auth/challenges/test_id/verify', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['code']);
    }

    public function testEnrollFactor(): void
    {
        $fixture = $this->loadFixture('authentication_factor_enrolled');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->enrollFactor(type: \WorkOS\Resource\AuthenticationFactorsCreateRequestType::GenericOtp);
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticationFactorEnrolled::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('auth/factors/enroll', $request->getUri()->getPath());
    }

    public function testGetFactor(): void
    {
        $fixture = $this->loadFixture('authentication_factor');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->getFactor('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticationFactor::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('auth/factors/test_id', $request->getUri()->getPath());
    }

    public function testDeleteFactor(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->multiFactorAuth()->deleteFactor('test_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('auth/factors/test_id', $request->getUri()->getPath());
    }

    public function testChallengeFactor(): void
    {
        $fixture = $this->loadFixture('authentication_challenge');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->challengeFactor('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticationChallenge::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['authentication_factor_id'], $result->authenticationFactorId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('auth/factors/test_id/challenge', $request->getUri()->getPath());
    }

    public function testListUserAuthFactors(): void
    {
        $fixture = $this->loadFixture('list_authentication_factor');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->listUserAuthFactors('test_userlandUserId', before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal);
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_userlandUserId/auth_factors', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
    }

    public function testCreateUserAuthFactor(): void
    {
        $fixture = $this->loadFixture('user_authentication_factor_enroll_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->createUserAuthFactor('test_userlandUserId', type: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\UserAuthenticationFactorEnrollResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_userlandUserId/auth_factors', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertArrayHasKey('type', $body);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_authentication_factor');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->multiFactorAuth()->listUserAuthFactors('test_userlandUserId');
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
