<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use WorkOS\TestHelper;

class PipesTest extends TestCase
{
    use TestHelper;

    public function testListDataIntegrations(): void
    {
        $fixture = $this->loadFixture('list_data_integration');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->listDataIntegrations(before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\PaginationOrder::Normal);
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('data-integrations', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
    }

    public function testCreateDataIntegration(): void
    {
        $fixture = $this->loadFixture('data_integration');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->createDataIntegration(provider: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegration::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['slug'], $result->slug);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('data-integrations', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['provider']);
    }

    public function testGetDataIntegration(): void
    {
        $fixture = $this->loadFixture('data_integration');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->getDataIntegration('test_slug');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegration::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['slug'], $result->slug);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_slug', $request->getUri()->getPath());
    }

    public function testUpdateDataIntegration(): void
    {
        $fixture = $this->loadFixture('data_integration');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->updateDataIntegration('test_slug');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegration::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['slug'], $result->slug);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_slug', $request->getUri()->getPath());
    }

    public function testDeleteDataIntegration(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->pipes()->deleteDataIntegration('test_slug');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_slug', $request->getUri()->getPath());
    }

    public function testUpdateDataIntegrationApiKey(): void
    {
        $fixture = $this->loadFixture('connected_account');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->updateDataIntegrationApiKey('test_slug', userId: 'test_value', secret: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\ConnectedAccount::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['created_at'], $result->createdAt);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_slug/api-key', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['user_id']);
        $this->assertSame('test_value', $body['secret']);
    }

    public function testAuthorizeDataIntegration(): void
    {
        $fixture = $this->loadFixture('data_integration_authorize_url_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->authorizeDataIntegration('test_slug', userId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegrationAuthorizeUrlResponse::class, $result);
        $this->assertSame($fixture['url'], $result->url);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_slug/authorize', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['user_id']);
    }

    public function testCreateDataIntegrationCredential(): void
    {
        $fixture = $this->loadFixture('data_integration_credentials_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->createDataIntegrationCredential('test_slug', userId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegrationCredentialsResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_slug/credentials', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['user_id']);
    }

    public function testGetAccessToken(): void
    {
        $fixture = $this->loadFixture('data_integration_access_token_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->getAccessToken('test_provider', userId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegrationAccessTokenResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('data-integrations/test_provider/token', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['user_id']);
    }

    public function testGetUserConnectedAccount(): void
    {
        $fixture = $this->loadFixture('connected_account');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->getUserConnectedAccount('test_user_id', 'test_slug');
        $this->assertInstanceOf(\WorkOS\Resource\ConnectedAccount::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['created_at'], $result->createdAt);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/connected_accounts/test_slug', $request->getUri()->getPath());
    }

    public function testCreateUserConnectedAccount(): void
    {
        $fixture = $this->loadFixture('connected_account');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->createUserConnectedAccount('test_user_id', 'test_slug');
        $this->assertInstanceOf(\WorkOS\Resource\ConnectedAccount::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['created_at'], $result->createdAt);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/connected_accounts/test_slug', $request->getUri()->getPath());
    }

    public function testUpdateUserConnectedAccount(): void
    {
        $fixture = $this->loadFixture('connected_account');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->updateUserConnectedAccount('test_user_id', 'test_slug');
        $this->assertInstanceOf(\WorkOS\Resource\ConnectedAccount::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['created_at'], $result->createdAt);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/connected_accounts/test_slug', $request->getUri()->getPath());
    }

    public function testDeleteUserConnectedAccount(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->pipes()->deleteUserConnectedAccount('test_user_id', 'test_slug');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/connected_accounts/test_slug', $request->getUri()->getPath());
    }

    public function testListUserDataProviders(): void
    {
        $fixture = $this->loadFixture('data_integrations_list_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->listUserDataProviders('test_user_id');
        $this->assertInstanceOf(\WorkOS\Resource\DataIntegrationsListResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/data_providers', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_data_integration');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->pipes()->listDataIntegrations();
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
