<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use WorkOS\TestHelper;

class RadarTest extends TestCase
{
    use TestHelper;

    public function testCreateAttempts(): void
    {
        $fixture = $this->loadFixture('radar_standalone_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->radar()->createAttempts(ipAddress: 'test_value', userAgent: 'test_value', email: 'test_value', authMethod: \WorkOS\Resource\RadarStandaloneAssessRequestAuthMethod::Password, action: \WorkOS\Resource\RadarStandaloneAssessRequestAction::Login);
        $this->assertInstanceOf(\WorkOS\Resource\RadarStandaloneResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('radar/attempts', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['ip_address']);
        $this->assertSame('test_value', $body['user_agent']);
        $this->assertSame('test_value', $body['email']);
    }

    public function testUpdateAttempt(): void
    {
        $client = $this->createMockClient([['status' => 200, 'body' => []]]);
        $client->radar()->updateAttempt('test_id');
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('radar/attempts/test_id', $request->getUri()->getPath());
    }

    public function testAddListEntry(): void
    {
        $fixture = $this->loadFixture('radar_list_entry_already_present_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->radar()->addListEntry(\WorkOS\Resource\RadarType::IpAddress, \WorkOS\Resource\RadarAction::Block, entry: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\RadarListEntryAlreadyPresentResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('radar/lists/ip_address/block', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['entry']);
    }

    public function testRemoveListEntry(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->radar()->removeListEntry(\WorkOS\Resource\RadarType::IpAddress, \WorkOS\Resource\RadarAction::Block, entry: 'test_value');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('radar/lists/ip_address/block', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['entry']);
    }
}
