<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use WorkOS\TestHelper;

class UserManagementTest extends TestCase
{
    use TestHelper;

    public function testGetJwks(): void
    {
        $fixture = $this->loadFixture('jwks_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getJwks('test_clientId');
        $this->assertInstanceOf(\WorkOS\Resource\JwksResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('sso/jwks/test_clientId', $request->getUri()->getPath());
    }

    public function testGetAuthorizationUrl(): void
    {
        $client = $this->createMockClient([]);
        $result = $client->userManagement()->getAuthorizationUrl(codeChallengeMethod: 'test_value', codeChallenge: 'test_value', domainHint: 'test_value', connectionId: 'test_value', providerQueryParams: [], providerScopes: [], invitationToken: 'test_value', screenHint: \WorkOS\Resource\UserManagementAuthenticationScreenHint::SignUp, loginHint: 'test_value', provider: \WorkOS\Resource\UserManagementAuthenticationProvider::Authkit, prompt: 'test_value', state: 'test_value', organizationId: 'test_value', redirectUri: 'test_value');
        $this->assertIsString($result);
        $this->assertStringContainsString('user_management/authorize', $result);
        parse_str(parse_url($result, PHP_URL_QUERY) ?? '', $query);
        $this->assertSame('test_value', $query['code_challenge']);
        $this->assertSame('test_value', $query['domain_hint']);
        $this->assertSame('test_value', $query['connection_id']);
        $this->assertSame('test_value', $query['invitation_token']);
        $this->assertSame('sign-up', $query['screen_hint']);
        $this->assertSame('test_value', $query['login_hint']);
        $this->assertSame('authkit', $query['provider']);
        $this->assertSame('test_value', $query['prompt']);
        $this->assertSame('test_value', $query['state']);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['redirect_uri']);
        $this->assertSame('code', $query['response_type']);
        $this->assertArrayHasKey('client_id', $query);
    }

    public function testCreateDevice(): void
    {
        $fixture = $this->loadFixture('device_authorization_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->createDevice(clientId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\DeviceAuthorizationResponse::class, $result);
        $this->assertSame($fixture['device_code'], $result->deviceCode);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/authorize/device', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['client_id']);
    }

    public function testGetLogoutUrl(): void
    {
        $client = $this->createMockClient([]);
        $result = $client->userManagement()->getLogoutUrl(sessionId: 'test_value', returnTo: 'test_value');
        $this->assertIsString($result);
        $this->assertStringContainsString('user_management/sessions/logout', $result);
        parse_str(parse_url($result, PHP_URL_QUERY) ?? '', $query);
        $this->assertSame('test_value', $query['session_id']);
        $this->assertSame('test_value', $query['return_to']);
    }

    public function testRevokeSession(): void
    {
        $client = $this->createMockClient([['status' => 200, 'body' => []]]);
        $client->userManagement()->revokeSession(sessionId: 'test_value');
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/sessions/revoke', $request->getUri()->getPath());
    }

    public function testCreateCorsOrigin(): void
    {
        $fixture = $this->loadFixture('cors_origin_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->createCorsOrigin(origin: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\CORSOriginResponse::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['origin'], $result->origin);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/cors_origins', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['origin']);
    }

    public function testGetEmailVerification(): void
    {
        $fixture = $this->loadFixture('email_verification');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getEmailVerification('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\EmailVerification::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/email_verification/test_id', $request->getUri()->getPath());
    }

    public function testResetPassword(): void
    {
        $fixture = $this->loadFixture('password_reset');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->resetPassword(email: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\PasswordReset::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/password_reset', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['email']);
    }

    public function testConfirmPasswordReset(): void
    {
        $fixture = $this->loadFixture('reset_password_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->confirmPasswordReset(token: 'test_value', newPassword: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\ResetPasswordResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/password_reset/confirm', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['token']);
        $this->assertSame('test_value', $body['new_password']);
    }

    public function testGetPasswordReset(): void
    {
        $fixture = $this->loadFixture('password_reset');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getPasswordReset('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\PasswordReset::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/password_reset/test_id', $request->getUri()->getPath());
    }

    public function testListUsers(): void
    {
        $fixture = $this->loadFixture('list_user');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->listUsers(before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal, organization: 'test_value', organizationId: 'test_value', email: 'test_value');
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
        $this->assertSame('test_value', $query['organization']);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['email']);
    }

    public function testCreateUser(): void
    {
        $fixture = $this->loadFixture('user');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->createUser(email: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\User::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['email']);
    }

    public function testGetUserByExternalId(): void
    {
        $fixture = $this->loadFixture('user');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getUserByExternalId('test_external_id');
        $this->assertInstanceOf(\WorkOS\Resource\User::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/external_id/test_external_id', $request->getUri()->getPath());
    }

    public function testGetUser(): void
    {
        $fixture = $this->loadFixture('user');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getUser('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\User::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id', $request->getUri()->getPath());
    }

    public function testUpdateUser(): void
    {
        $fixture = $this->loadFixture('user');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->updateUser('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\User::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id', $request->getUri()->getPath());
    }

    public function testDeleteUser(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->userManagement()->deleteUser('test_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id', $request->getUri()->getPath());
    }

    public function testConfirmEmailChange(): void
    {
        $fixture = $this->loadFixture('email_change_confirmation');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->confirmEmailChange('test_id', code: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\EmailChangeConfirmation::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id/email_change/confirm', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['code']);
    }

    public function testSendEmailChange(): void
    {
        $fixture = $this->loadFixture('email_change');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->sendEmailChange('test_id', newEmail: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\EmailChange::class, $result);
        $this->assertSame($fixture['new_email'], $result->newEmail);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id/email_change/send', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['new_email']);
    }

    public function testVerifyEmail(): void
    {
        $fixture = $this->loadFixture('verify_email_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->verifyEmail('test_id', code: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\VerifyEmailResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id/email_verification/confirm', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['code']);
    }

    public function testSendVerificationEmail(): void
    {
        $fixture = $this->loadFixture('send_verification_email_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->sendVerificationEmail('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\SendVerificationEmailResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id/email_verification/send', $request->getUri()->getPath());
    }

    public function testGetUserIdentities(): void
    {
        $fixture = $this->loadFixture('user_identities_get_item');
        $client = $this->createMockClient([['status' => 200, 'body' => [$fixture]]]);
        $result = $client->userManagement()->getUserIdentities('test_id');
        $this->assertIsArray($result);
        $this->assertInstanceOf(\WorkOS\Resource\UserIdentitiesGetItem::class, $result[0]);
        $this->assertSame($fixture['idp_id'], $result[0]->idpId);
        $this->assertIsArray($result[0]->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id/identities', $request->getUri()->getPath());
    }

    public function testListSessions(): void
    {
        $fixture = $this->loadFixture('list_user_sessions_list_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->listSessions('test_id', before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal);
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_id/sessions', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
    }

    public function testListInvitations(): void
    {
        $fixture = $this->loadFixture('list_user_invite');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->listInvitations(before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal, organizationId: 'test_value', email: 'test_value');
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['email']);
    }

    public function testSendInvitation(): void
    {
        $fixture = $this->loadFixture('user_invite');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->sendInvitation(email: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\UserInvite::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['email']);
    }

    public function testFindInvitationByToken(): void
    {
        $fixture = $this->loadFixture('user_invite');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->findInvitationByToken('test_token');
        $this->assertInstanceOf(\WorkOS\Resource\UserInvite::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations/by_token/test_token', $request->getUri()->getPath());
    }

    public function testGetInvitation(): void
    {
        $fixture = $this->loadFixture('user_invite');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getInvitation('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\UserInvite::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations/test_id', $request->getUri()->getPath());
    }

    public function testAcceptInvitation(): void
    {
        $fixture = $this->loadFixture('invitation');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->acceptInvitation('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\Invitation::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations/test_id/accept', $request->getUri()->getPath());
    }

    public function testResendInvitation(): void
    {
        $fixture = $this->loadFixture('user_invite');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->resendInvitation('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\UserInvite::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations/test_id/resend', $request->getUri()->getPath());
    }

    public function testRevokeInvitation(): void
    {
        $fixture = $this->loadFixture('invitation');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->revokeInvitation('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\Invitation::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['email'], $result->email);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/invitations/test_id/revoke', $request->getUri()->getPath());
    }

    public function testUpdateJWTTemplate(): void
    {
        $fixture = $this->loadFixture('jwt_template_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->updateJWTTemplate(content: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\JWTTemplateResponse::class, $result);
        $this->assertSame($fixture['content'], $result->content);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('user_management/jwt_template', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['content']);
    }

    public function testCreateMagicAuth(): void
    {
        $fixture = $this->loadFixture('magic_auth');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->createMagicAuth(email: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\MagicAuth::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/magic_auth', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['email']);
    }

    public function testGetMagicAuth(): void
    {
        $fixture = $this->loadFixture('magic_auth');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getMagicAuth('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\MagicAuth::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/magic_auth/test_id', $request->getUri()->getPath());
    }

    public function testListOrganizationMemberships(): void
    {
        $fixture = $this->loadFixture('list_user_organization_membership');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->listOrganizationMemberships(before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal, organizationId: 'test_value', statuses: [], userId: 'test_value');
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['user_id']);
    }

    public function testCreateOrganizationMembership(): void
    {
        $fixture = $this->loadFixture('organization_membership');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->createOrganizationMembership(userId: 'test_value', organizationId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\OrganizationMembership::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['user_id']);
        $this->assertSame('test_value', $body['organization_id']);
    }

    public function testGetOrganizationMembership(): void
    {
        $fixture = $this->loadFixture('user_organization_membership');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->getOrganizationMembership('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\UserOrganizationMembership::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships/test_id', $request->getUri()->getPath());
    }

    public function testUpdateOrganizationMembership(): void
    {
        $fixture = $this->loadFixture('user_organization_membership');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->updateOrganizationMembership('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\UserOrganizationMembership::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships/test_id', $request->getUri()->getPath());
    }

    public function testDeleteOrganizationMembership(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->userManagement()->deleteOrganizationMembership('test_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships/test_id', $request->getUri()->getPath());
    }

    public function testDeactivateOrganizationMembership(): void
    {
        $fixture = $this->loadFixture('organization_membership');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->deactivateOrganizationMembership('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\OrganizationMembership::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships/test_id/deactivate', $request->getUri()->getPath());
    }

    public function testReactivateOrganizationMembership(): void
    {
        $fixture = $this->loadFixture('user_organization_membership');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->reactivateOrganizationMembership('test_id');
        $this->assertInstanceOf(\WorkOS\Resource\UserOrganizationMembership::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['user_id'], $result->userId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('user_management/organization_memberships/test_id/reactivate', $request->getUri()->getPath());
    }

    public function testCreateRedirectUri(): void
    {
        $fixture = $this->loadFixture('redirect_uri');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->createRedirectUri(uri: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\RedirectUri::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['uri'], $result->uri);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('user_management/redirect_uris', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['uri']);
    }

    public function testListUserAuthorizedApplications(): void
    {
        $fixture = $this->loadFixture('list_authorized_connect_application_list_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->listUserAuthorizedApplications('test_user_id', before: 'test_value', after: 'test_value', limit: 1, order: \WorkOS\Resource\EventsOrder::Normal);
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/authorized_applications', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('normal', $query['order']);
    }

    public function testDeleteUserAuthorizedApplication(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->userManagement()->deleteUserAuthorizedApplication('test_application_id', 'test_user_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('user_management/users/test_user_id/authorized_applications/test_application_id', $request->getUri()->getPath());
    }

    public function testAuthenticateWithPassword(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithPassword(email: 'test_value', password: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithCode(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithCode(code: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithRefreshToken(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithRefreshToken(refreshToken: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithMagicAuth(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithMagicAuth(code: 'test_value', email: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithEmailVerification(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithEmailVerification(code: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithTotp(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithTotp(code: 'test_value', pendingAuthenticationToken: 'test_value', authenticationChallengeId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithOrganizationSelection(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithOrganizationSelection(pendingAuthenticationToken: 'test_value', organizationId: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testAuthenticateWithDeviceCode(): void
    {
        $fixture = $this->loadFixture('authenticate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->authenticateWithDeviceCode(deviceCode: 'test_value');
        $this->assertInstanceOf(\WorkOS\Resource\AuthenticateResponse::class, $result);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_user');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->userManagement()->listUsers();
        $this->assertInstanceOf(\WorkOS\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
