<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\PortalLinkResponse;

class AdminPortal
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * Generate a Portal Link
     *
     * Generate a Portal Link scoped to an Organization.
     * @param string|null $returnUrl The URL to go to when an admin clicks on your logo in the Admin Portal. If not specified, the return URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
     * @param string|null $successUrl The URL to redirect the admin to when they finish setup. If not specified, the success URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
     * @param string $organization An [Organization](https://workos.com/docs/reference/organization) identifier.
     * @param \WorkOS\Resource\GenerateLinkIntent|null $intent
     *       The intent of the Admin Portal.
     *         - `sso` - Launch Admin Portal for creating SSO connections
     *         - `dsync` - Launch Admin Portal for creating Directory Sync connections
     *         - `audit_logs` - Launch Admin Portal for viewing Audit Logs
     *         - `log_streams` - Launch Admin Portal for creating Log Streams
     *         - `domain_verification` - Launch Admin Portal for Domain Verification
     *         - `certificate_renewal` - Launch Admin Portal for renewing SAML Certificates
     *         - `bring_your_own_key` - Launch Admin Portal for configuring Bring Your Own Key
     * @param \WorkOS\Resource\IntentOptions|null $intentOptions Options to configure the Admin Portal based on the intent.
     * @param array<string>|null $adminEmails The email addresses of the IT admins to grant access to the Admin Portal for the given organization. Accepts up to 20 emails.
     * @return \WorkOS\Resource\PortalLinkResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function generateLink(
        string $organization,
        ?string $returnUrl = null,
        ?string $successUrl = null,
        ?\WorkOS\Resource\GenerateLinkIntent $intent = null,
        ?\WorkOS\Resource\IntentOptions $intentOptions = null,
        ?array $adminEmails = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\PortalLinkResponse {
        $body = array_filter([
            'return_url' => $returnUrl,
            'success_url' => $successUrl,
            'organization' => $organization,
            'intent' => $intent?->value,
            'intent_options' => $intentOptions,
            'admin_emails' => $adminEmails,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'portal/generate_link',
            body: $body,
            options: $options,
        );
        return PortalLinkResponse::fromArray($response);
    }
}
