<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\ApiKey;
use WorkOS\Resource\ApiKeyValidationResponse;
use WorkOS\Resource\ApiKeyWithValue;

class ApiKeys
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * Validate API key
     *
     * Validate an API key value and return the API key object if valid.
     * @param string $value The value for an API key.
     * @return \WorkOS\Resource\ApiKeyValidationResponse
     */
    public function createValidations(
        string $value,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ApiKeyValidationResponse {
        $body = [
            'value' => $value,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'api_keys/validations',
            body: $body,
            options: $options,
        );
        return ApiKeyValidationResponse::fromArray($response);
    }

    /**
     * Delete an API key
     *
     * Permanently deletes an API key. This action cannot be undone. Once deleted, any requests using this API key will fail authentication.
     * @param string $id The unique ID of the API key.
     * @return void
     */
    public function deleteApiKey(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "api_keys/{$id}",
            options: $options,
        );
    }

    /**
     * List API keys for an organization
     *
     * Get a list of all API keys for an organization.
     * @param string $organizationId Unique identifier of the Organization.
     * @param string|null $before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param string|null $after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param float|null $limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param \WorkOS\Resource\EventsOrder|null $order Order the results by the creation time.
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\ApiKey>
     */
    public function listOrganizationApiKeys(
        string $organizationId,
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\EventsOrder $order = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order?->value,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: "organizations/{$organizationId}/api_keys",
            query: $query,
            modelClass: ApiKey::class,
            options: $options,
        );
    }

    /**
     * Create an API key for an organization
     *
     * Create a new API key for an organization.
     * @param string $organizationId Unique identifier of the Organization.
     * @param string $name The name for the API key.
     * @param array<string>|null $permissions The permission slugs to assign to the API key.
     * @return \WorkOS\Resource\ApiKeyWithValue
     */
    public function createOrganizationApiKeys(
        string $organizationId,
        string $name,
        ?array $permissions = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ApiKeyWithValue {
        $body = array_filter([
            'name' => $name,
            'permissions' => $permissions,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: "organizations/{$organizationId}/api_keys",
            body: $body,
            options: $options,
        );
        return ApiKeyWithValue::fromArray($response);
    }
}
