<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\PaginatedResponse;
use WorkOS\Resource\AuditLogActionJson;
use WorkOS\Resource\AuditLogEventCreateResponse;
use WorkOS\Resource\AuditLogExportJson;
use WorkOS\Resource\AuditLogSchemaJson;
use WorkOS\Resource\AuditLogsRetentionJson;

class AuditLogs
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    public function listOrganizationAuditLogsRetention(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuditLogsRetentionJson {
        $response = $this->client->request(
            method: 'GET',
            path: "organizations/{$id}/audit_logs_retention",
            options: $options,
        );
        return AuditLogsRetentionJson::fromArray($response);
    }

    public function updateOrganizationAuditLogsRetention(
        string $id,
        int $retentionPeriodInDays,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuditLogsRetentionJson {
        $body = [
            'retention_period_in_days' => $retentionPeriodInDays,
        ];
        $response = $this->client->request(
            method: 'PUT',
            path: "organizations/{$id}/audit_logs_retention",
            body: $body,
            options: $options,
        );
        return AuditLogsRetentionJson::fromArray($response);
    }

    public function listActions(
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\AuditLogsOrder $order = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'audit_logs/actions',
            query: $query,
            options: $options,
        );
        return PaginatedResponse::fromArray($response, AuditLogActionJson::class);
    }

    public function listActionSchemas(
        string $actionName,
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\AuditLogsOrder $order = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: "audit_logs/actions/{$actionName}/schemas",
            query: $query,
            options: $options,
        );
        return PaginatedResponse::fromArray($response, AuditLogSchemaJson::class);
    }

    public function createActionSchemas(
        string $actionName,
        array $targets,
        ?\WorkOS\Resource\AuditLogSchemaActor $actor = null,
        ?array $metadata = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuditLogSchemaJson {
        $body = array_filter([
            'actor' => $actor,
            'targets' => $targets,
            'metadata' => $metadata,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: "audit_logs/actions/{$actionName}/schemas",
            body: $body,
            options: $options,
        );
        return AuditLogSchemaJson::fromArray($response);
    }

    public function createEvents(
        string $organizationId,
        \WorkOS\Resource\AuditLogEvent $event,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuditLogEventCreateResponse {
        $body = [
            'organization_id' => $organizationId,
            'event' => $event,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'audit_logs/events',
            body: $body,
            options: $options,
        );
        return AuditLogEventCreateResponse::fromArray($response);
    }

    public function createExports(
        string $organizationId,
        string $rangeStart,
        string $rangeEnd,
        ?array $actions = null,
        ?array $actors = null,
        ?array $actorNames = null,
        ?array $actorIds = null,
        ?array $targets = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuditLogExportJson {
        $body = array_filter([
            'organization_id' => $organizationId,
            'range_start' => $rangeStart,
            'range_end' => $rangeEnd,
            'actions' => $actions,
            'actors' => $actors,
            'actor_names' => $actorNames,
            'actor_ids' => $actorIds,
            'targets' => $targets,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'audit_logs/exports',
            body: $body,
            options: $options,
        );
        return AuditLogExportJson::fromArray($response);
    }

    public function getExport(
        string $auditLogExportId,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuditLogExportJson {
        $response = $this->client->request(
            method: 'GET',
            path: "audit_logs/exports/{$auditLogExportId}",
            options: $options,
        );
        return AuditLogExportJson::fromArray($response);
    }
}
