<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\AuthorizationCheck;
use WorkOS\Resource\AuthorizationPermission;
use WorkOS\Resource\AuthorizationResource;
use WorkOS\Resource\ListModel;
use WorkOS\Resource\Permission;
use WorkOS\Resource\Role;
use WorkOS\Resource\RoleAssignment;
use WorkOS\Resource\RoleList;
use WorkOS\Resource\UserOrganizationMembershipBaseListData;

class Authorization
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    public function checkOrganizationMembership(
        string $organizationMembershipId,
        string $permissionSlug,
        ?string $resourceId = null,
        ?string $resourceExternalId = null,
        ?string $resourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationCheck {
        $body = array_filter([
            'permission_slug' => $permissionSlug,
            'resource_id' => $resourceId,
            'resource_external_id' => $resourceExternalId,
            'resource_type_slug' => $resourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: "authorization/organization_memberships/{$organizationMembershipId}/check",
            body: $body,
            options: $options,
        );
        return AuthorizationCheck::fromArray($response);
    }

    public function listOrganizationMembershipResources(
        string $organizationMembershipId,
        string $permissionSlug,
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\AuthorizationOrder $order = null,
        ?string $parentResourceId = null,
        ?string $parentResourceTypeSlug = null,
        ?string $parentResourceExternalId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
            'permission_slug' => $permissionSlug,
            'parent_resource_id' => $parentResourceId,
            'parent_resource_type_slug' => $parentResourceTypeSlug,
            'parent_resource_external_id' => $parentResourceExternalId,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: "authorization/organization_memberships/{$organizationMembershipId}/resources",
            query: $query,
            modelClass: AuthorizationResource::class,
            options: $options,
        );
    }

    public function listOrganizationMembershipRoleAssignments(
        string $organizationMembershipId,
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\AuthorizationOrder $order = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: "authorization/organization_memberships/{$organizationMembershipId}/role_assignments",
            query: $query,
            modelClass: RoleAssignment::class,
            options: $options,
        );
    }

    public function createOrganizationMembershipRoleAssignments(
        string $organizationMembershipId,
        string $roleSlug,
        ?string $resourceId = null,
        ?string $resourceExternalId = null,
        ?string $resourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\RoleAssignment {
        $body = array_filter([
            'role_slug' => $roleSlug,
            'resource_id' => $resourceId,
            'resource_external_id' => $resourceExternalId,
            'resource_type_slug' => $resourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: "authorization/organization_memberships/{$organizationMembershipId}/role_assignments",
            body: $body,
            options: $options,
        );
        return RoleAssignment::fromArray($response);
    }

    public function deleteOrganizationMembershipRoleAssignments(
        string $organizationMembershipId,
        string $roleSlug,
        ?string $resourceId = null,
        ?string $resourceExternalId = null,
        ?string $resourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $body = array_filter([
            'role_slug' => $roleSlug,
            'resource_id' => $resourceId,
            'resource_external_id' => $resourceExternalId,
            'resource_type_slug' => $resourceTypeSlug,
        ], fn ($v) => $v !== null);
        $this->client->request(
            method: 'DELETE',
            path: "authorization/organization_memberships/{$organizationMembershipId}/role_assignments",
            body: $body,
            options: $options,
        );
    }

    public function deleteOrganizationMembershipRoleAssignment(
        string $organizationMembershipId,
        string $roleAssignmentId,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "authorization/organization_memberships/{$organizationMembershipId}/role_assignments/{$roleAssignmentId}",
            options: $options,
        );
    }

    public function listOrganizationRoles(
        string $organizationId,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ListModel {
        $response = $this->client->request(
            method: 'GET',
            path: "authorization/organizations/{$organizationId}/roles",
            options: $options,
        );
        return ListModel::fromArray($response);
    }

    public function createOrganizationRoles(
        string $organizationId,
        string $name,
        ?string $slug = null,
        ?string $description = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $body = array_filter([
            'slug' => $slug,
            'name' => $name,
            'description' => $description,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: "authorization/organizations/{$organizationId}/roles",
            body: $body,
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function getOrganizationRole(
        string $organizationId,
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $response = $this->client->request(
            method: 'GET',
            path: "authorization/organizations/{$organizationId}/roles/{$slug}",
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function updateOrganizationRole(
        string $organizationId,
        string $slug,
        ?string $name = null,
        ?string $description = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: "authorization/organizations/{$organizationId}/roles/{$slug}",
            body: $body,
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function deleteOrganizationRole(
        string $organizationId,
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "authorization/organizations/{$organizationId}/roles/{$slug}",
            options: $options,
        );
    }

    public function createRolePermissions(
        string $organizationId,
        string $slug,
        string $bodySlug,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $body = [
            'slug' => $bodySlug,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: "authorization/organizations/{$organizationId}/roles/{$slug}/permissions",
            body: $body,
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function updateRolePermissions(
        string $organizationId,
        string $slug,
        array $permissions,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $body = [
            'permissions' => $permissions,
        ];
        $response = $this->client->request(
            method: 'PUT',
            path: "authorization/organizations/{$organizationId}/roles/{$slug}/permissions",
            body: $body,
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function deleteRolePermission(
        string $organizationId,
        string $slug,
        string $permissionSlug,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "authorization/organizations/{$organizationId}/roles/{$slug}/permissions/{$permissionSlug}",
            options: $options,
        );
    }

    public function getOrganizationResource(
        string $organizationId,
        string $resourceTypeSlug,
        string $externalId,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationResource {
        $response = $this->client->request(
            method: 'GET',
            path: "authorization/organizations/{$organizationId}/resources/{$resourceTypeSlug}/{$externalId}",
            options: $options,
        );
        return AuthorizationResource::fromArray($response);
    }

    public function updateOrganizationResource(
        string $organizationId,
        string $resourceTypeSlug,
        string $externalId,
        ?string $name = null,
        ?string $description = null,
        ?string $parentResourceId = null,
        ?string $parentResourceExternalId = null,
        ?string $parentResourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationResource {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
            'parent_resource_id' => $parentResourceId,
            'parent_resource_external_id' => $parentResourceExternalId,
            'parent_resource_type_slug' => $parentResourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: "authorization/organizations/{$organizationId}/resources/{$resourceTypeSlug}/{$externalId}",
            body: $body,
            options: $options,
        );
        return AuthorizationResource::fromArray($response);
    }

    public function deleteOrganizationResource(
        string $organizationId,
        string $resourceTypeSlug,
        string $externalId,
        ?bool $cascadeDelete = null,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $query = array_filter([
            'cascade_delete' => $cascadeDelete,
        ], fn ($v) => $v !== null);
        $this->client->request(
            method: 'DELETE',
            path: "authorization/organizations/{$organizationId}/resources/{$resourceTypeSlug}/{$externalId}",
            query: $query,
            options: $options,
        );
    }

    public function listResourceOrganizationMemberships(
        string $organizationId,
        string $resourceTypeSlug,
        string $externalId,
        string $permissionSlug,
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\AuthorizationOrder $order = null,
        ?\WorkOS\Resource\AuthorizationAssignment $assignment = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
            'permission_slug' => $permissionSlug,
            'assignment' => $assignment,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: "authorization/organizations/{$organizationId}/resources/{$resourceTypeSlug}/{$externalId}/organization_memberships",
            query: $query,
            modelClass: UserOrganizationMembershipBaseListData::class,
            options: $options,
        );
    }

    public function listResources(
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\AuthorizationOrder $order = null,
        ?string $organizationId = null,
        ?string $resourceTypeSlug = null,
        ?string $parentResourceId = null,
        ?string $parentResourceTypeSlug = null,
        ?string $parentExternalId = null,
        ?string $search = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
            'organization_id' => $organizationId,
            'resource_type_slug' => $resourceTypeSlug,
            'parent_resource_id' => $parentResourceId,
            'parent_resource_type_slug' => $parentResourceTypeSlug,
            'parent_external_id' => $parentExternalId,
            'search' => $search,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'authorization/resources',
            query: $query,
            modelClass: AuthorizationResource::class,
            options: $options,
        );
    }

    public function createResources(
        string $externalId,
        string $name,
        string $resourceTypeSlug,
        string $organizationId,
        ?string $description = null,
        ?string $parentResourceId = null,
        ?string $parentResourceExternalId = null,
        ?string $parentResourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationResource {
        $body = array_filter([
            'external_id' => $externalId,
            'name' => $name,
            'description' => $description,
            'resource_type_slug' => $resourceTypeSlug,
            'organization_id' => $organizationId,
            'parent_resource_id' => $parentResourceId,
            'parent_resource_external_id' => $parentResourceExternalId,
            'parent_resource_type_slug' => $parentResourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'authorization/resources',
            body: $body,
            options: $options,
        );
        return AuthorizationResource::fromArray($response);
    }

    public function getResource(
        string $resourceId,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationResource {
        $response = $this->client->request(
            method: 'GET',
            path: "authorization/resources/{$resourceId}",
            options: $options,
        );
        return AuthorizationResource::fromArray($response);
    }

    public function updateResource(
        string $resourceId,
        ?string $name = null,
        ?string $description = null,
        ?string $parentResourceId = null,
        ?string $parentResourceExternalId = null,
        ?string $parentResourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationResource {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
            'parent_resource_id' => $parentResourceId,
            'parent_resource_external_id' => $parentResourceExternalId,
            'parent_resource_type_slug' => $parentResourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: "authorization/resources/{$resourceId}",
            body: $body,
            options: $options,
        );
        return AuthorizationResource::fromArray($response);
    }

    public function deleteResource(
        string $resourceId,
        ?bool $cascadeDelete = null,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $query = array_filter([
            'cascade_delete' => $cascadeDelete,
        ], fn ($v) => $v !== null);
        $this->client->request(
            method: 'DELETE',
            path: "authorization/resources/{$resourceId}",
            query: $query,
            options: $options,
        );
    }

    public function listRoles(
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\RoleList {
        $response = $this->client->request(
            method: 'GET',
            path: 'authorization/roles',
            options: $options,
        );
        return RoleList::fromArray($response);
    }

    public function createRoles(
        string $slug,
        string $name,
        ?string $description = null,
        ?string $resourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $body = array_filter([
            'slug' => $slug,
            'name' => $name,
            'description' => $description,
            'resource_type_slug' => $resourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'authorization/roles',
            body: $body,
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function getRole(
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $response = $this->client->request(
            method: 'GET',
            path: "authorization/roles/{$slug}",
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function updateRole(
        string $slug,
        ?string $name = null,
        ?string $description = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Role {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: "authorization/roles/{$slug}",
            body: $body,
            options: $options,
        );
        return Role::fromArray($response);
    }

    public function listPermissions(
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\PermissionsOrder $order = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'authorization/permissions',
            query: $query,
            modelClass: AuthorizationPermission::class,
            options: $options,
        );
    }

    public function createPermissions(
        string $slug,
        string $name,
        ?string $description = null,
        ?string $resourceTypeSlug = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Permission {
        $body = array_filter([
            'slug' => $slug,
            'name' => $name,
            'description' => $description,
            'resource_type_slug' => $resourceTypeSlug,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'authorization/permissions',
            body: $body,
            options: $options,
        );
        return Permission::fromArray($response);
    }

    public function getPermission(
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationPermission {
        $response = $this->client->request(
            method: 'GET',
            path: "authorization/permissions/{$slug}",
            options: $options,
        );
        return AuthorizationPermission::fromArray($response);
    }

    public function updatePermission(
        string $slug,
        ?string $name = null,
        ?string $description = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\AuthorizationPermission {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: "authorization/permissions/{$slug}",
            body: $body,
            options: $options,
        );
        return AuthorizationPermission::fromArray($response);
    }

    public function deletePermission(
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "authorization/permissions/{$slug}",
            options: $options,
        );
    }
}
