<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\ClientApiTokenResponse;

class ClientApi
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * Generate a Client API token
     *
     * Generate a short-lived, session-bound token for the Client GraphQL API, scoped to an organization and user.
     * @param string $organizationId The ID of the organization to scope the Client API token to.
     * @param string $userId The ID of the user to issue the Client API token for.
     * @return \WorkOS\Resource\ClientApiTokenResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createToken(
        string $organizationId,
        string $userId,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ClientApiTokenResponse {
        $body = [
            'organization_id' => $organizationId,
            'user_id' => $userId,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'client/token',
            body: $body,
            options: $options,
        );
        return ClientApiTokenResponse::fromArray($response);
    }
}
