<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\ApplicationCredentialsListItem;
use WorkOS\Resource\ConnectApplication;
use WorkOS\Resource\ExternalAuthCompleteResponse;
use WorkOS\Resource\NewConnectApplicationSecret;

class Connect
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * Complete external authentication
     *
     * Completes an external authentication flow and returns control to AuthKit. This endpoint is used with [Standalone Connect](https://workos.com/docs/authkit/connect/standalone) to bridge your existing authentication system with the Connect OAuth API infrastructure.
     *
     * After successfully authenticating a user in your application, calling this endpoint will:
     *
     * - Create or update the user in AuthKit, using the given `id` as its `external_id`.
     * - Return a `redirect_uri` your application should redirect to in order for AuthKit to complete the flow
     *
     * Users are automatically created or updated based on the `id` and `email` provided. If a user with the same `id` exists, their information is updated. Otherwise, a new user is created.
     *
     * If you provide a new `id` with an `email` that already belongs to an existing user, the request will fail with an error as email addresses are unique to a user.
     * @param string $externalAuthId Identifier provided when AuthKit redirected to your login page.
     * @param \WorkOS\Resource\UserObject $user The user to create or update in AuthKit.
     * @param array<\WorkOS\Resource\UserConsentOption>|null $userConsentOptions Array of [User Consent Options](https://workos.com/docs/reference/workos-connect/standalone/user-consent-options) to store with the session.
     * @return \WorkOS\Resource\ExternalAuthCompleteResponse
     */
    public function completeOAuth2(
        string $externalAuthId,
        \WorkOS\Resource\UserObject $user,
        ?array $userConsentOptions = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ExternalAuthCompleteResponse {
        $body = array_filter([
            'external_auth_id' => $externalAuthId,
            'user' => $user,
            'user_consent_options' => $userConsentOptions,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'authkit/oauth2/complete',
            body: $body,
            options: $options,
        );
        return ExternalAuthCompleteResponse::fromArray($response);
    }

    /**
     * List Connect Applications
     *
     * List all Connect Applications in the current environment with optional filtering.
     * @param string|null $before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param string|null $after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param float|null $limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param \WorkOS\Resource\EventsOrder|null $order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
     * @param string|null $organizationId Filter Connect Applications by organization ID.
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\ConnectApplication>
     */
    public function listApplications(
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\EventsOrder $order = null,
        ?string $organizationId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order?->value,
            'organization_id' => $organizationId,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'connect/applications',
            query: $query,
            modelClass: ConnectApplication::class,
            options: $options,
        );
    }

    /**
     * Create a Connect Application
     *
     * Create a new Connect Application. Supports both OAuth and Machine-to-Machine (M2M) application types.
     * @return \WorkOS\Resource\ConnectApplication
     */
    public function createApplications(
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectApplication {
        $body = [
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'connect/applications',
            body: $body,
            options: $options,
        );
        return ConnectApplication::fromArray($response);
    }

    /**
     * @param mixed|null $name
     * @param mixed|null $isFirstParty
     * @param mixed|null $description
     * @param mixed|null $scopes
     * @param mixed|null $redirectUris
     * @param mixed|null $usesPkce
     * @param mixed|null $organizationId
     * @return \WorkOS\Resource\ConnectApplication
     */
    public function createOAuthApplication(
        mixed $name = null,
        mixed $isFirstParty = null,
        mixed $description = null,
        mixed $scopes = null,
        mixed $redirectUris = null,
        mixed $usesPkce = null,
        mixed $organizationId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectApplication {
        $body = array_filter([
            'application_type' => 'oauth',
            'name' => $name,
            'is_first_party' => $isFirstParty,
            'description' => $description,
            'scopes' => $scopes,
            'redirect_uris' => $redirectUris,
            'uses_pkce' => $usesPkce,
            'organization_id' => $organizationId,
        ], fn ($v) => $v !== null);

        $response = $this->client->request(
            method: 'POST',
            path: 'connect/applications',
            body: $body,
            options: $options,
        );
        return ConnectApplication::fromArray($response);
    }

    /**
     * @param mixed|null $name
     * @param mixed|null $organizationId
     * @param mixed|null $description
     * @param mixed|null $scopes
     * @return \WorkOS\Resource\ConnectApplication
     */
    public function createM2MApplication(
        mixed $name = null,
        mixed $organizationId = null,
        mixed $description = null,
        mixed $scopes = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectApplication {
        $body = array_filter([
            'application_type' => 'm2m',
            'name' => $name,
            'organization_id' => $organizationId,
            'description' => $description,
            'scopes' => $scopes,
        ], fn ($v) => $v !== null);

        $response = $this->client->request(
            method: 'POST',
            path: 'connect/applications',
            body: $body,
            options: $options,
        );
        return ConnectApplication::fromArray($response);
    }

    /**
     * Get a Connect Application
     *
     * Retrieve details for a specific Connect Application by ID or client ID.
     * @param string $id The application ID or client ID of the Connect Application.
     * @return \WorkOS\Resource\ConnectApplication
     */
    public function getApplication(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectApplication {
        $response = $this->client->request(
            method: 'GET',
            path: "connect/applications/{$id}",
            options: $options,
        );
        return ConnectApplication::fromArray($response);
    }

    /**
     * Update a Connect Application
     *
     * Update an existing Connect Application. For OAuth applications, you can update redirect URIs. For all applications, you can update the name, description, and scopes.
     * @param string $id The application ID or client ID of the Connect Application.
     * @param string|null $name The name of the application.
     * @param string|null|null $description A description for the application.
     * @param array<string>|null|null $scopes The OAuth scopes granted to the application.
     * @param array<\WorkOS\Resource\RedirectUriInput>|null|null $redirectUris Updated redirect URIs for the application. OAuth applications only.
     * @return \WorkOS\Resource\ConnectApplication
     */
    public function updateApplication(
        string $id,
        ?string $name = null,
        ?string $description = null,
        ?array $scopes = null,
        ?array $redirectUris = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectApplication {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
            'scopes' => $scopes,
            'redirect_uris' => $redirectUris,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: "connect/applications/{$id}",
            body: $body,
            options: $options,
        );
        return ConnectApplication::fromArray($response);
    }

    /**
     * Delete a Connect Application
     *
     * Delete an existing Connect Application.
     * @param string $id The application ID or client ID of the Connect Application.
     * @return void
     */
    public function deleteApplication(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "connect/applications/{$id}",
            options: $options,
        );
    }

    /**
     * List Client Secrets for a Connect Application
     *
     * List all client secrets associated with a Connect Application.
     * @param string $id The application ID or client ID of the Connect Application.
     * @return array
     */
    public function listApplicationClientSecrets(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): array {
        $response = $this->client->request(
            method: 'GET',
            path: "connect/applications/{$id}/client_secrets",
            options: $options,
        );
        return array_map(fn ($item) => ApplicationCredentialsListItem::fromArray($item), $response);
    }

    /**
     * Create a new client secret for a Connect Application
     *
     * Create new secrets for a Connect Application.
     * @param string $id The application ID or client ID of the Connect Application.
     * @return \WorkOS\Resource\NewConnectApplicationSecret
     */
    public function createApplicationClientSecrets(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\NewConnectApplicationSecret {
        $body = [
        ];
        $response = $this->client->request(
            method: 'POST',
            path: "connect/applications/{$id}/client_secrets",
            body: $body,
            options: $options,
        );
        return NewConnectApplicationSecret::fromArray($response);
    }

    /**
     * Delete a Client Secret
     *
     * Delete (revoke) an existing client secret.
     * @param string $id The unique ID of the client secret.
     * @return void
     */
    public function deleteClientSecret(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "connect/client_secrets/{$id}",
            options: $options,
        );
    }
}
