<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\Directory;
use WorkOS\Resource\DirectoryGroup;
use WorkOS\Resource\DirectoryUserWithGroups;

class DirectorySync
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * List Directories
     *
     * Get a list of all of your existing directories matching the criteria specified.
     * @param string|null $before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param string|null $after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param int|null $limit Upper limit on the number of objects to return, between `1` and `100`. Defaults to 10.
     * @param \WorkOS\Resource\EventsOrder $order Order the results by the creation time. Defaults to "desc".
     * @param string|null $organizationId Filter Directories by their associated organization.
     * @param string|null $search Searchable text to match against Directory names.
     * @param string|null $domain (deprecated) Filter Directories by their associated domain.
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\Directory>
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listDirectories(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \WorkOS\Resource\EventsOrder $order = \WorkOS\Resource\EventsOrder::Desc,
        ?string $organizationId = null,
        ?string $search = null,
        ?string $domain = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'organization_id' => $organizationId,
            'search' => $search,
            'domain' => $domain,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'directories',
            query: $query,
            modelClass: Directory::class,
            options: $options,
        );
    }

    /**
     * Get a Directory
     *
     * Get the details of an existing directory.
     * @param string $id Unique identifier for the Directory.
     * @return \WorkOS\Resource\Directory
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getDirectory(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\Directory {
        $response = $this->client->request(
            method: 'GET',
            path: "directories/{$id}",
            options: $options,
        );
        return Directory::fromArray($response);
    }

    /**
     * Delete a Directory
     *
     * Permanently deletes an existing directory. It cannot be undone.
     * @param string $id Unique identifier for the Directory.
     * @return void
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function deleteDirectory(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: "directories/{$id}",
            options: $options,
        );
    }

    /**
     * List Directory Groups
     *
     * Get a list of all of existing directory groups matching the criteria specified.
     * @param string|null $before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param string|null $after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param int|null $limit Upper limit on the number of objects to return, between `1` and `100`. Defaults to 10.
     * @param \WorkOS\Resource\EventsOrder $order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending. Defaults to "desc".
     * @param string|null $directory Unique identifier of the WorkOS Directory. This value can be obtained from the WorkOS dashboard or from the WorkOS API.
     * @param string|null $user Unique identifier of the WorkOS Directory User. This value can be obtained from the WorkOS API.
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\DirectoryGroup>
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listGroups(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \WorkOS\Resource\EventsOrder $order = \WorkOS\Resource\EventsOrder::Desc,
        ?string $directory = null,
        ?string $user = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'directory' => $directory,
            'user' => $user,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'directory_groups',
            query: $query,
            modelClass: DirectoryGroup::class,
            options: $options,
        );
    }

    /**
     * Get a Directory Group
     *
     * Get the details of an existing Directory Group.
     * @param string $id Unique identifier for the Directory Group.
     * @return \WorkOS\Resource\DirectoryGroup
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getGroup(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DirectoryGroup {
        $response = $this->client->request(
            method: 'GET',
            path: "directory_groups/{$id}",
            options: $options,
        );
        return DirectoryGroup::fromArray($response);
    }

    /**
     * List Directory Users
     *
     * Get a list of all of existing Directory Users matching the criteria specified.
     * @param string|null $before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param string|null $after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param int|null $limit Upper limit on the number of objects to return, between `1` and `100`. Defaults to 10.
     * @param \WorkOS\Resource\EventsOrder $order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending. Defaults to "desc".
     * @param string|null $directory Unique identifier of the WorkOS Directory. This value can be obtained from the WorkOS dashboard or from the WorkOS API.
     * @param string|null $group Unique identifier of the WorkOS Directory Group. This value can be obtained from the WorkOS API.
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\DirectoryUserWithGroups>
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listUsers(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \WorkOS\Resource\EventsOrder $order = \WorkOS\Resource\EventsOrder::Desc,
        ?string $directory = null,
        ?string $group = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'directory' => $directory,
            'group' => $group,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'directory_users',
            query: $query,
            modelClass: DirectoryUserWithGroups::class,
            options: $options,
        );
    }

    /**
     * Get a Directory User
     *
     * Get the details of an existing Directory User.
     * @param string $id Unique identifier for the Directory User.
     * @return \WorkOS\Resource\DirectoryUserWithGroups
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getUser(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DirectoryUserWithGroups {
        $response = $this->client->request(
            method: 'GET',
            path: "directory_users/{$id}",
            options: $options,
        );
        return DirectoryUserWithGroups::fromArray($response);
    }
}
