<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\PaginatedResponse;
use WorkOS\Resource\EventSchema;

class Events
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    public function listEvents(
        ?string $before = null,
        ?string $after = null,
        ?float $limit = null,
        ?\WorkOS\Resource\EventsOrder $order = null,
        ?array $events = null,
        ?string $rangeStart = null,
        ?string $rangeEnd = null,
        ?string $organizationId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order,
            'events' => $events,
            'range_start' => $rangeStart,
            'range_end' => $rangeEnd,
            'organization_id' => $organizationId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'events',
            query: $query,
            options: $options,
        );
        return PaginatedResponse::fromArray($response, EventSchema::class);
    }
}
