<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

class ParentResourceByExternalId
{
    public function __construct(
        public readonly string $externalId,
        public readonly string $typeSlug,
    ) {
    }
}
