<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

class PatchProtocolOptionsSAML
{
    public function __construct(
        public readonly \WorkOS\Resource\PatchConnectionSAMLOptions $samlOptions,
    ) {
    }
}
