<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\ConnectedAccount;
use WorkOS\Resource\DataIntegration;
use WorkOS\Resource\DataIntegrationAccessTokenResponse;
use WorkOS\Resource\DataIntegrationAuthorizeUrlResponse;
use WorkOS\Resource\DataIntegrationCredentialsResponse;
use WorkOS\Resource\DataIntegrationsListResponse;

class Pipes
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * List data integrations
     *
     * Lists the environment's data integrations configured with `custom` or `organization` credentials, including custom providers and API key integrations.
     * @param string|null $before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param string|null $after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param int|null $limit Upper limit on the number of objects to return, between `1` and `100`. Defaults to 10.
     * @param \WorkOS\Resource\PaginationOrder $order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to "desc".
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\DataIntegration>
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listDataIntegrations(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \WorkOS\Resource\PaginationOrder $order = \WorkOS\Resource\PaginationOrder::Desc,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'data-integrations',
            query: $query,
            modelClass: DataIntegration::class,
            options: $options,
        );
    }

    /**
     * Create a data integration
     *
     * Creates a data integration for a provider. Set `credentials.type` to `custom` to use your own OAuth app credentials or `organization` to have each organization supply its own. Set `auth_methods` to `["api_key"]` to create an API key integration; you may optionally supply an `api_key` block to install a first tenant in the same call. Set `auth_methods` to `["client_credentials"]` to create a client-credentials integration; client credentials are installed per-tenant afterwards. For a built-in provider, pass its slug as `provider`. For a custom provider, pass a new slug plus a `custom_provider` definition.
     * @param string $provider The provider to create a Data Integration for. For a built-in provider use its slug (e.g. `github`, `slack`). For a custom provider, this is the new provider slug and `custom_provider` must be supplied. A custom provider slug cannot shadow an existing global provider slug.
     * @param string|null $description An optional description of the Data Integration.
     * @param bool|null $enabled Whether the Data Integration is enabled. Defaults to `false`.
     * @param array<string>|null $scopes The OAuth scopes to request for the Data Integration. Defaults to the provider's configured scopes when omitted.
     * @param array<\WorkOS\Resource\DataIntegrationAuthMethods>|null $authMethods How accounts authenticate with the provider. Defaults to `["oauth"]`. Use `["api_key"]` to declare an API key integration; `credentials` is then not required and keys are supplied per-tenant (optionally via `api_key` on this request). Use `["client_credentials"]` to declare a client-credentials integration; `credentials` is likewise not required and client credentials are supplied per-tenant.
     * @param array<string, string>|null $config Provider-specific config values (e.g. a Snowflake `account`), keyed by the config field. Only fields the built-in provider declares are accepted.
     * @param \WorkOS\Resource\DataIntegrationCredentialsInput|null $credentials The OAuth credentials to configure for the Data Integration. Required for OAuth integrations; omit when `auth_methods` is `["api_key"]`.
     * @param \WorkOS\Resource\ApiKeyInstallation|null $apiKey An optional API key to install for the first tenant on an `api_key` integration. Omit to declare a keyless integration; tenants can be added later via the per-installation API key path.
     * @param \WorkOS\Resource\CustomProviderDefinition|null $customProvider The OAuth definition for a custom provider. Supply this to define a custom provider; omit it to create an integration for a built-in provider.
     * @return \WorkOS\Resource\DataIntegration
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createDataIntegration(
        string $provider,
        ?string $description = null,
        ?bool $enabled = null,
        ?array $scopes = null,
        ?array $authMethods = null,
        ?array $config = null,
        ?\WorkOS\Resource\DataIntegrationCredentialsInput $credentials = null,
        ?\WorkOS\Resource\ApiKeyInstallation $apiKey = null,
        ?\WorkOS\Resource\CustomProviderDefinition $customProvider = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegration {
        $body = array_filter([
            'provider' => $provider,
            'description' => $description,
            'enabled' => $enabled,
            'scopes' => $scopes,
            'auth_methods' => $authMethods,
            'config' => $config,
            'credentials' => $credentials,
            'api_key' => $apiKey,
            'custom_provider' => $customProvider,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'data-integrations',
            body: $body,
            options: $options,
        );
        return DataIntegration::fromArray($response);
    }

    /**
     * Get a data integration
     *
     * Retrieves a data integration by its slug.
     * @param string $slug The slug identifier of the data integration.
     * @return \WorkOS\Resource\DataIntegration
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getDataIntegration(
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegration {
        $response = $this->client->request(
            method: 'GET',
            path: 'data-integrations/' . rawurlencode($slug),
            options: $options,
        );
        return DataIntegration::fromArray($response);
    }

    /**
     * Update a data integration
     *
     * Updates the description, enabled state, or custom credentials of a data integration. For custom providers, `custom_provider` updates the OAuth definition.
     * @param string $slug The slug identifier of the data integration.
     * @param string|null $description An optional description of the Data Integration.
     * @param bool|null $enabled Whether the Data Integration is enabled.
     * @param array<string>|null $scopes The OAuth scopes to request for the Data Integration. Pass `null` to reset to the provider's configured scopes.
     * @param \WorkOS\Resource\DataIntegrationCredentialsInput|null $credentials New OAuth credentials for the Data Integration. When provided, rotates the stored client secret. Mutually exclusive with `api_key`.
     * @param \WorkOS\Resource\ApiKeyInstallation|null $apiKey An API key to install or rotate for a tenant on an `api_key` integration. Upserts the tenant installation identified by `user_id` (and optional `organization_id`).
     * @param \WorkOS\Resource\UpdateCustomProviderDefinition|null $customProvider Updates to a custom provider's OAuth definition. Only valid for custom-provider integrations.
     * @return \WorkOS\Resource\DataIntegration
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function updateDataIntegration(
        string $slug,
        ?string $description = null,
        ?bool $enabled = null,
        ?array $scopes = null,
        ?\WorkOS\Resource\DataIntegrationCredentialsInput $credentials = null,
        ?\WorkOS\Resource\ApiKeyInstallation $apiKey = null,
        ?\WorkOS\Resource\UpdateCustomProviderDefinition $customProvider = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegration {
        $body = array_filter([
            'description' => $description,
            'enabled' => $enabled,
            'scopes' => $scopes,
            'credentials' => $credentials,
            'api_key' => $apiKey,
            'custom_provider' => $customProvider,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: 'data-integrations/' . rawurlencode($slug),
            body: $body,
            options: $options,
        );
        return DataIntegration::fromArray($response);
    }

    /**
     * Delete a data integration
     *
     * Deletes a data integration and all of its connected installations. For a custom provider, also deletes the custom provider definition.
     * @param string $slug The slug identifier of the data integration.
     * @return void
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function deleteDataIntegration(
        string $slug,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'data-integrations/' . rawurlencode($slug),
            options: $options,
        );
    }

    /**
     * Upsert an API key for a connected account
     *
     * Creates or updates an API-key-based installation for the specified integration and user. If an installation already exists, the stored API key is rotated to the new value.
     * @param string $slug The identifier of the integration.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param string $secret The API key secret to store for this integration.
     * @return \WorkOS\Resource\ConnectedAccount
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function updateDataIntegrationApiKey(
        string $slug,
        string $userId,
        string $secret,
        ?string $organizationId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectedAccount {
        $body = array_filter([
            'user_id' => $userId,
            'organization_id' => $organizationId,
            'secret' => $secret,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: 'data-integrations/' . rawurlencode($slug) . '/api-key',
            body: $body,
            options: $options,
        );
        return ConnectedAccount::fromArray($response);
    }

    /**
     * Get authorization URL
     *
     * Generates an OAuth authorization URL to initiate the connection flow for a user. Redirect the user to the returned URL to begin the OAuth flow with the third-party provider.
     * @param string $slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param string $userId The ID of the user to authorize.
     * @param string|null $organizationId An organization ID to scope the authorization to a specific organization.
     * @param string|null $returnTo The URL to redirect the user to after authorization.
     * @param array<string, string>|null $config Connect-time config values for the provider-declared `installation`-scope fields (e.g. a Zendesk `subdomain`), keyed by the config field. Only fields the provider declares may be supplied, and required fields must be provided unless already pinned on the integration.
     * @return \WorkOS\Resource\DataIntegrationAuthorizeUrlResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function authorizeDataIntegration(
        string $slug,
        string $userId,
        ?string $organizationId = null,
        ?string $returnTo = null,
        ?array $config = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegrationAuthorizeUrlResponse {
        $body = array_filter([
            'user_id' => $userId,
            'organization_id' => $organizationId,
            'return_to' => $returnTo,
            'config' => $config,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'data-integrations/' . rawurlencode($slug) . '/authorize',
            body: $body,
            options: $options,
        );
        return DataIntegrationAuthorizeUrlResponse::fromArray($response);
    }

    /**
     * Upsert client credentials for a connected account
     *
     * Creates or updates a client-credentials-based installation for the specified integration and user. If an installation already exists, the stored client credentials are rotated to the new values.
     * @param string $slug The identifier of the integration.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param string $clientId The OAuth client ID to store for this integration.
     * @param string $clientSecret The OAuth client secret to store for this integration.
     * @param array<string, string>|null $config Provider-specific configuration values collected for this installation, keyed by the provider's config field descriptors.
     * @return \WorkOS\Resource\ConnectedAccount
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function updateDataIntegrationClientCredentials(
        string $slug,
        string $userId,
        string $clientId,
        string $clientSecret,
        ?string $organizationId = null,
        ?array $config = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectedAccount {
        $body = array_filter([
            'user_id' => $userId,
            'organization_id' => $organizationId,
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'config' => $config,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: 'data-integrations/' . rawurlencode($slug) . '/client-credentials',
            body: $body,
            options: $options,
        );
        return ConnectedAccount::fromArray($response);
    }

    /**
     * Vend credentials for a connected account
     *
     * Returns credentials for a user's connected account. Branches on the installation's `auth_method`: OAuth installations return an access token (refreshed if needed); API-key installations return the stored secret.
     * @param string $slug The identifier of the integration.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param string|null $connectedAccountId A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select a specific connection when the user has several for this provider.
     * @return \WorkOS\Resource\DataIntegrationCredentialsResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createDataIntegrationCredential(
        string $slug,
        string $userId,
        ?string $organizationId = null,
        ?string $connectedAccountId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegrationCredentialsResponse {
        $body = array_filter([
            'user_id' => $userId,
            'organization_id' => $organizationId,
            'connected_account_id' => $connectedAccountId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'data-integrations/' . rawurlencode($slug) . '/credentials',
            body: $body,
            options: $options,
        );
        return DataIntegrationCredentialsResponse::fromArray($response);
    }

    /**
     * Get an access token for a connected account
     *
     * Fetches a valid OAuth access token for a user's connected account. WorkOS automatically handles token refresh, ensuring you always receive a valid, non-expired token.
     * @param string $provider The identifier of the integration.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param string|null $connectedAccountId A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select a specific connection when the user has several for this provider.
     * @return \WorkOS\Resource\DataIntegrationAccessTokenResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getAccessToken(
        string $provider,
        string $userId,
        ?string $organizationId = null,
        ?string $connectedAccountId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegrationAccessTokenResponse {
        $body = array_filter([
            'user_id' => $userId,
            'organization_id' => $organizationId,
            'connected_account_id' => $connectedAccountId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'data-integrations/' . rawurlencode($provider) . '/token',
            body: $body,
            options: $options,
        );
        return DataIntegrationAccessTokenResponse::fromArray($response);
    }

    /**
     * Get a connected account
     *
     * Retrieves a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for a specific provider.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string $slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param string|null $connectedAccountId A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select a specific connection when the user has several for this provider.
     * @return \WorkOS\Resource\ConnectedAccount
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getUserConnectedAccount(
        string $userId,
        string $slug,
        ?string $organizationId = null,
        ?string $connectedAccountId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectedAccount {
        $query = array_filter([
            'organization_id' => $organizationId,
            'connected_account_id' => $connectedAccountId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'user_management/users/' . rawurlencode($userId) . '/connected_accounts/' . rawurlencode($slug),
            query: $query,
            options: $options,
        );
        return ConnectedAccount::fromArray($response);
    }

    /**
     * Import a connected account
     *
     * Imports a [connected account](https://workos.com/docs/reference/pipes/connected-account) for a user by providing OAuth tokens directly. Use this to migrate existing connections or set up connections without going through the OAuth flow.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string $slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param string|null $accessToken The OAuth access token for the connected account.
     * @param string|null $refreshToken The OAuth refresh token for the connected account.
     * @param \DateTimeImmutable|null $expiresAt The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
     * @param array<string>|null $scopes The OAuth scopes granted for this connection.
     * @param \WorkOS\Resource\PipeConnectedAccountState|null $state Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @return \WorkOS\Resource\ConnectedAccount
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createUserConnectedAccount(
        string $userId,
        string $slug,
        ?string $accessToken = null,
        ?string $refreshToken = null,
        ?\DateTimeImmutable $expiresAt = null,
        ?array $scopes = null,
        ?\WorkOS\Resource\PipeConnectedAccountState $state = null,
        ?string $organizationId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectedAccount {
        $body = array_filter([
            'access_token' => $accessToken,
            'refresh_token' => $refreshToken,
            'expires_at' => $expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'scopes' => $scopes,
            'state' => $state?->value,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'user_management/users/' . rawurlencode($userId) . '/connected_accounts/' . rawurlencode($slug),
            body: $body,
            options: $options,
        );
        return ConnectedAccount::fromArray($response);
    }

    /**
     * Update a connected account
     *
     * Updates a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) tokens, scopes, or state for a specific provider.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string $slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param string|null $accessToken The OAuth access token for the connected account.
     * @param string|null $refreshToken The OAuth refresh token for the connected account.
     * @param \DateTimeImmutable|null $expiresAt The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
     * @param array<string>|null $scopes The OAuth scopes granted for this connection.
     * @param \WorkOS\Resource\PipeConnectedAccountState|null $state Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param string|null $connectedAccountId A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select the connection to update.
     * @return \WorkOS\Resource\ConnectedAccount
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function updateUserConnectedAccount(
        string $userId,
        string $slug,
        ?string $accessToken = null,
        ?string $refreshToken = null,
        ?\DateTimeImmutable $expiresAt = null,
        ?array $scopes = null,
        ?\WorkOS\Resource\PipeConnectedAccountState $state = null,
        ?string $organizationId = null,
        ?string $connectedAccountId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ConnectedAccount {
        $body = array_filter([
            'access_token' => $accessToken,
            'refresh_token' => $refreshToken,
            'expires_at' => $expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'scopes' => $scopes,
            'state' => $state?->value,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: 'user_management/users/' . rawurlencode($userId) . '/connected_accounts/' . rawurlencode($slug),
            body: $body,
            options: $options,
        );
        return ConnectedAccount::fromArray($response);
    }

    /**
     * Delete a connected account
     *
     * Disconnects WorkOS's account for the user, including removing any stored access and refresh tokens. The user will need to reauthorize if they want to reconnect. This does not revoke access on the provider side.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param string $slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param string|null $connectedAccountId A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select the connection to delete.
     * @return void
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function deleteUserConnectedAccount(
        string $userId,
        string $slug,
        ?string $organizationId = null,
        ?string $connectedAccountId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $query = array_filter([
            'organization_id' => $organizationId,
            'connected_account_id' => $connectedAccountId,
        ], fn ($v) => $v !== null);
        $this->client->request(
            method: 'DELETE',
            path: 'user_management/users/' . rawurlencode($userId) . '/connected_accounts/' . rawurlencode($slug),
            query: $query,
            options: $options,
        );
    }

    /**
     * List providers for a user
     *
     * Retrieves a list of available providers and the user's connection status for each. Returns all providers configured for your environment, along with the user's [connected account](https://workos.com/docs/reference/pipes/connected-account) information where applicable.
     * @param string $userId A [User](https://workos.com/docs/reference/authkit/user) identifier to list providers and connected accounts for.
     * @param string|null $organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to filter connections for a specific organization.
     * @return \WorkOS\Resource\DataIntegrationsListResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listUserDataProviders(
        string $userId,
        ?string $organizationId = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DataIntegrationsListResponse {
        $query = array_filter([
            'organization_id' => $organizationId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'user_management/users/' . rawurlencode($userId) . '/data_providers',
            query: $query,
            options: $options,
        );
        return DataIntegrationsListResponse::fromArray($response);
    }
}
