<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\RadarListEntryAlreadyPresentResponse;
use WorkOS\Resource\RadarStandaloneResponse;

class Radar
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    public function createAttempts(
        string $ipAddress,
        string $userAgent,
        string $email,
        \WorkOS\Resource\RadarStandaloneAssessRequestAuthMethod $authMethod,
        \WorkOS\Resource\RadarStandaloneAssessRequestAction $action,
        ?string $deviceFingerprint = null,
        ?string $botScore = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\RadarStandaloneResponse {
        $body = array_filter([
            'ip_address' => $ipAddress,
            'user_agent' => $userAgent,
            'email' => $email,
            'auth_method' => $authMethod,
            'action' => $action,
            'device_fingerprint' => $deviceFingerprint,
            'bot_score' => $botScore,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'radar/attempts',
            body: $body,
            options: $options,
        );
        return RadarStandaloneResponse::fromArray($response);
    }

    public function updateAttempt(
        string $id,
        ?string $challengeStatus = null,
        ?string $attemptStatus = null,
        ?\WorkOS\RequestOptions $options = null,
    ): mixed {
        $body = array_filter([
            'challenge_status' => $challengeStatus,
            'attempt_status' => $attemptStatus,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: "radar/attempts/{$id}",
            body: $body,
            options: $options,
        );
        return $response;
    }

    public function addListEntry(
        \WorkOS\Resource\RadarType $type,
        \WorkOS\Resource\RadarAction $action,
        string $entry,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\RadarListEntryAlreadyPresentResponse {
        $body = [
            'entry' => $entry,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: "radar/lists/{$type->value}/{$action->value}",
            body: $body,
            options: $options,
        );
        return RadarListEntryAlreadyPresentResponse::fromArray($response);
    }

    public function removeListEntry(
        \WorkOS\Resource\RadarType $type,
        \WorkOS\Resource\RadarAction $action,
        string $entry,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $body = [
            'entry' => $entry,
        ];
        $this->client->request(
            method: 'DELETE',
            path: "radar/lists/{$type->value}/{$action->value}",
            body: $body,
            options: $options,
        );
    }
}
