<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS\Service;

use WorkOS\Resource\CreateDataKeyResponse;
use WorkOS\Resource\DecryptResponse;
use WorkOS\Resource\ObjectMetadata;
use WorkOS\Resource\ObjectSummary;
use WorkOS\Resource\ObjectWithoutValue;
use WorkOS\Resource\VaultObject;
use WorkOS\Resource\VersionListResponse;

class Vault
{
    public function __construct(
        private readonly \WorkOS\HttpClient $client,
    ) {
    }

    /**
     * Create a data key
     *
     * Generate an isolated encryption key for local encryption operations.
     * @param array<string, string> $context Map of values used to determine the encryption key.
     * @return \WorkOS\Resource\CreateDataKeyResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createDataKey(
        array $context,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\CreateDataKeyResponse {
        $body = [
            'context' => $context,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'vault/v1/keys/data-key',
            body: $body,
            options: $options,
        );
        return CreateDataKeyResponse::fromArray($response);
    }

    /**
     * Decrypt a data key
     *
     * Decrypt a previously encrypted data key from WorkOS Vault.
     * @param string $keys Base64-encoded encrypted data key to decrypt.
     * @return \WorkOS\Resource\DecryptResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createDecrypt(
        string $keys,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\DecryptResponse {
        $body = [
            'keys' => $keys,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'vault/v1/keys/decrypt',
            body: $body,
            options: $options,
        );
        return DecryptResponse::fromArray($response);
    }

    /**
     * Re-encrypt a data key
     *
     * Decrypt an existing data key and re-encrypt it under a new key context.
     * @param array<string, string> $context Map of values used to determine the new encryption key.
     * @param string $encryptedKeys Base64-encoded encrypted data key blob to re-encrypt.
     * @return \WorkOS\Resource\CreateDataKeyResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createRekey(
        array $context,
        string $encryptedKeys,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\CreateDataKeyResponse {
        $body = [
            'context' => $context,
            'encrypted_keys' => $encryptedKeys,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'vault/v1/keys/rekey',
            body: $body,
            options: $options,
        );
        return CreateDataKeyResponse::fromArray($response);
    }

    /**
     * List objects
     *
     * List all encrypted objects with cursor-based pagination.
     * @param int|null $limit Upper limit on the number of objects to return. Defaults to 10.
     * @param string|null $before Cursor for the previous page of results.
     * @param string|null $after Cursor for the next page of results.
     * @param \WorkOS\Resource\VaultOrder|null $order Sort direction for results.
     * @param string|null $search Filter results by name or structured search JSON.
     * @param \DateTimeImmutable|null $updatedAfter ISO 8601 timestamp to filter by last modified time.
     * @return \WorkOS\PaginatedResponse<\WorkOS\Resource\ObjectSummary>
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listKv(
        ?int $limit = null,
        ?string $before = null,
        ?string $after = null,
        ?\WorkOS\Resource\VaultOrder $order = null,
        ?string $search = null,
        ?\DateTimeImmutable $updatedAfter = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\PaginatedResponse {
        $query = array_filter([
            'limit' => $limit,
            'before' => $before,
            'after' => $after,
            'order' => $order?->value,
            'search' => $search,
            'updatedAfter' => $updatedAfter?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'vault/v1/kv',
            query: $query,
            modelClass: ObjectSummary::class,
            options: $options,
        );
    }

    /**
     * Create an object
     *
     * Encrypt and store a new key-value object.
     * @param array<string, string> $keyContext Map of values used to determine the encryption key.
     * @param string $name Unique name for the object.
     * @param string $value Plaintext data to encrypt and store.
     * @return \WorkOS\Resource\ObjectMetadata
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function createKv(
        array $keyContext,
        string $name,
        string $value,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ObjectMetadata {
        $body = [
            'key_context' => $keyContext,
            'name' => $name,
            'value' => $value,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'vault/v1/kv',
            body: $body,
            options: $options,
        );
        return ObjectMetadata::fromArray($response);
    }

    /**
     * Read an object by name
     *
     * Fetch and decrypt an object by its unique name.
     * @param string $name Unique name of the object.
     * @return \WorkOS\Resource\VaultObject
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getName(
        string $name,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\VaultObject {
        $response = $this->client->request(
            method: 'GET',
            path: 'vault/v1/kv/name/' . rawurlencode($name),
            options: $options,
        );
        return VaultObject::fromArray($response);
    }

    /**
     * Read an object by ID
     *
     * Fetch and decrypt an object by its unique identifier.
     * @param string $id Unique identifier of the object.
     * @return \WorkOS\Resource\VaultObject
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function getKv(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\VaultObject {
        $response = $this->client->request(
            method: 'GET',
            path: 'vault/v1/kv/' . rawurlencode($id),
            options: $options,
        );
        return VaultObject::fromArray($response);
    }

    /**
     * Update an object
     *
     * Update the value of an existing encrypted object.
     * @param string $id Unique identifier of the object.
     * @param string $value New plaintext value.
     * @param string|null $versionCheck ID of the expected current version for optimistic locking.
     * @return \WorkOS\Resource\ObjectWithoutValue
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function updateKv(
        string $id,
        string $value,
        ?string $versionCheck = null,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ObjectWithoutValue {
        $body = array_filter([
            'value' => $value,
            'version_check' => $versionCheck,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PUT',
            path: 'vault/v1/kv/' . rawurlencode($id),
            body: $body,
            options: $options,
        );
        return ObjectWithoutValue::fromArray($response);
    }

    /**
     * Delete an object
     *
     * Delete an encrypted object.
     * @param string $id Unique identifier of the object.
     * @param string|null $versionCheck Expected current version for optimistic locking.
     * @return void
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function deleteKv(
        string $id,
        ?string $versionCheck = null,
        ?\WorkOS\RequestOptions $options = null,
    ): void {
        $query = array_filter([
            'version_check' => $versionCheck,
        ], fn ($v) => $v !== null);
        $this->client->request(
            method: 'DELETE',
            path: 'vault/v1/kv/' . rawurlencode($id),
            query: $query,
            options: $options,
        );
    }

    /**
     * Describe an object
     *
     * Fetch metadata for an object without decrypting it.
     * @param string $id Unique identifier of the object.
     * @return \WorkOS\Resource\ObjectWithoutValue
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listKvMetadata(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\ObjectWithoutValue {
        $response = $this->client->request(
            method: 'GET',
            path: 'vault/v1/kv/' . rawurlencode($id) . '/metadata',
            options: $options,
        );
        return ObjectWithoutValue::fromArray($response);
    }

    /**
     * List object versions
     *
     * Retrieve all versions for a specific object.
     * @param string $id Unique identifier of the object.
     * @return \WorkOS\Resource\VersionListResponse
     * @throws \WorkOS\Exception\WorkOSException
     */
    public function listKvVersions(
        string $id,
        ?\WorkOS\RequestOptions $options = null,
    ): \WorkOS\Resource\VersionListResponse {
        $response = $this->client->request(
            method: 'GET',
            path: 'vault/v1/kv/' . rawurlencode($id) . '/versions',
            options: $options,
        );
        return VersionListResponse::fromArray($response);
    }

    // @oagen-ignore-start — client-side AES-GCM encrypt/decrypt (H18, vault_local_crypto)

    /**
     * Encrypt data locally using AES-GCM with a data key derived from the context.
     *
     * @param string $data The plaintext data to encrypt.
     * @param array<string, string> $context The key context for data key derivation.
     * @param string|null $associatedData Additional authenticated data (AAD).
     * @return string The base64-encoded encrypted payload.
     */
    public function encrypt(
        string $data,
        array $context,
        ?string $associatedData = null,
    ): string {
        $keyPair = $this->createDataKey($context);

        $key = base64_decode($keyPair->dataKey);
        $keyBlob = base64_decode($keyPair->encryptedKeys);
        $prefixLenBuffer = self::encodeU32Leb128(strlen($keyBlob));
        $iv = random_bytes(12);

        $result = self::aesGcmEncrypt($data, $key, $iv, $associatedData);

        $combined = $result['iv'] . $result['tag'] . $prefixLenBuffer . $keyBlob . $result['ciphertext'];
        return base64_encode($combined);
    }

    /**
     * Decrypt data that was previously encrypted using the encrypt method.
     *
     * @param string $encryptedData The base64-encoded encrypted payload.
     * @param string|null $associatedData Additional authenticated data (AAD).
     * @return string The decrypted plaintext.
     */
    public function decrypt(
        string $encryptedData,
        ?string $associatedData = null,
    ): string {
        $decoded = self::decodeEncryptedPayload($encryptedData);
        $dataKey = $this->createDecrypt($decoded['keys']);

        $key = base64_decode($dataKey->dataKey);

        return self::aesGcmDecrypt(
            $decoded['ciphertext'],
            $key,
            $decoded['iv'],
            $decoded['tag'],
            $associatedData,
        );
    }

    /**
     * @return array{ciphertext: string, iv: string, tag: string}
     */
    private static function aesGcmEncrypt(
        string $plaintext,
        string $key,
        string $iv,
        ?string $aad,
    ): array {
        $tag = '';
        $ciphertext = openssl_encrypt(
            $plaintext,
            'aes-256-gcm',
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag,
            $aad ?? '',
            16,
        );

        if ($ciphertext === false) {
            throw new \RuntimeException('AES-GCM encryption failed');
        }

        return ['ciphertext' => $ciphertext, 'iv' => $iv, 'tag' => $tag];
    }

    private static function aesGcmDecrypt(
        string $ciphertext,
        string $key,
        string $iv,
        string $tag,
        ?string $aad,
    ): string {
        $plaintext = openssl_decrypt(
            $ciphertext,
            'aes-256-gcm',
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag,
            $aad ?? '',
        );

        if ($plaintext === false) {
            throw new \RuntimeException('AES-GCM decryption failed');
        }

        return $plaintext;
    }

    private static function encodeU32Leb128(int $value): string
    {
        if ($value < 0 || $value > 0xFFFFFFFF) {
            throw new \InvalidArgumentException('Value must be a 32-bit unsigned integer');
        }

        $encoded = '';
        do {
            $byte = $value & 0x7F;
            $value >>= 7;
            if ($value !== 0) {
                $byte |= 0x80;
            }
            $encoded .= chr($byte);
        } while ($value !== 0);

        return $encoded;
    }

    /**
     * @return array{0: int, 1: int}
     */
    private static function decodeU32Leb128(string $buf): array
    {
        $res = 0;
        $bit = 0;
        $len = strlen($buf);

        for ($i = 0; $i < $len; $i++) {
            if ($i > 4) {
                throw new \InvalidArgumentException('LEB128 integer overflow');
            }
            $b = ord($buf[$i]);
            $res |= ($b & 0x7F) << (7 * $bit);
            if (($b & 0x80) === 0) {
                return [$res, $i + 1];
            }
            $bit++;
        }

        throw new \InvalidArgumentException('LEB128 integer not found');
    }

    /**
     * @return array{iv: string, tag: string, keys: string, ciphertext: string}
     */
    private static function decodeEncryptedPayload(string $encryptedDataB64): array
    {
        $payload = base64_decode($encryptedDataB64, true);
        if ($payload === false) {
            throw new \InvalidArgumentException('Base64 decoding failed');
        }

        $iv = substr($payload, 0, 12);
        $tag = substr($payload, 12, 16);
        [$keyLen, $lebLen] = self::decodeU32Leb128(substr($payload, 28));
        $keysIndex = 28 + $lebLen;
        $keysEnd = $keysIndex + $keyLen;
        $keysSlice = substr($payload, $keysIndex, $keyLen);
        $keys = base64_encode($keysSlice);
        $ciphertext = substr($payload, $keysEnd);

        return ['iv' => $iv, 'tag' => $tag, 'keys' => $keys, 'ciphertext' => $ciphertext];
    }

    // @oagen-ignore-end
}
