<?php

declare(strict_types=1);
// @oagen-ignore-file
// This file is hand-maintained. The vault API endpoints are not yet in the
// OpenAPI spec, so this module provides the functionality until they are.
// The encrypt/decrypt methods use client-side AES-GCM and will always be
// hand-maintained regardless of spec coverage.
// Covers: Vault HTTP endpoints + H18 (vault_local_crypto).

namespace WorkOS;

class Vault
{
    private const DEFAULT_RESPONSE_LIMIT = 10;

    public function __construct(
        private readonly HttpClient $client,
    ) {
    }

    // -- KV operations --

    /**
     * Get a Vault object with the value decrypted.
     */
    public function readObject(string $objectId): array
    {
        return $this->client->request(
            method: 'GET',
            path: "vault/v1/kv/{$objectId}",
        );
    }

    /**
     * Get a Vault object by name with the value decrypted.
     */
    public function readObjectByName(string $name): array
    {
        return $this->client->request(
            method: 'GET',
            path: "vault/v1/kv/name/{$name}",
        );
    }

    /**
     * Get a Vault object's metadata without decrypting the value.
     */
    public function getObjectMetadata(string $objectId): array
    {
        return $this->client->request(
            method: 'GET',
            path: "vault/v1/kv/{$objectId}/metadata",
        );
    }

    /**
     * Gets a list of encrypted Vault objects.
     */
    public function listObjects(
        int $limit = self::DEFAULT_RESPONSE_LIMIT,
        ?string $before = null,
        ?string $after = null,
    ): array {
        $query = array_filter([
            'limit' => $limit,
            'before' => $before,
            'after' => $after,
        ], fn ($v) => $v !== null);

        return $this->client->request(
            method: 'GET',
            path: 'vault/v1/kv',
            query: $query,
        );
    }

    /**
     * Gets a list of versions for a specific Vault object.
     */
    public function listObjectVersions(string $objectId): array
    {
        return $this->client->request(
            method: 'GET',
            path: "vault/v1/kv/{$objectId}/versions",
        );
    }

    /**
     * Create a new Vault encrypted object.
     */
    public function createObject(string $name, string $value, array $keyContext): array
    {
        return $this->client->request(
            method: 'POST',
            path: 'vault/v1/kv',
            body: [
                'name' => $name,
                'value' => $value,
                'key_context' => $keyContext,
            ],
        );
    }

    /**
     * Update an existing Vault object.
     */
    public function updateObject(
        string $objectId,
        string $value,
        ?string $versionCheck = null,
    ): array {
        $body = ['value' => $value];
        if ($versionCheck !== null) {
            $body['version_check'] = $versionCheck;
        }

        return $this->client->request(
            method: 'PUT',
            path: "vault/v1/kv/{$objectId}",
            body: $body,
        );
    }

    /**
     * Permanently delete a Vault encrypted object.
     */
    public function deleteObject(string $objectId): void
    {
        $this->client->request(
            method: 'DELETE',
            path: "vault/v1/kv/{$objectId}",
        );
    }

    // -- Key operations --

    /**
     * Generate a data key for local encryption.
     */
    public function createDataKey(array $keyContext): array
    {
        return $this->client->request(
            method: 'POST',
            path: 'vault/v1/keys/data-key',
            body: ['context' => $keyContext],
        );
    }

    /**
     * Decrypt encrypted data keys previously generated by createDataKey.
     */
    public function decryptDataKey(string $keys): array
    {
        return $this->client->request(
            method: 'POST',
            path: 'vault/v1/keys/decrypt',
            body: ['keys' => $keys],
        );
    }

    // -- Client-side encryption (H18) --

    /**
     * Encrypt data locally using AES-GCM with a data key derived from the context.
     *
     * @param string $data The plaintext data to encrypt.
     * @param array $keyContext The key context for data key derivation.
     * @param string|null $associatedData Additional authenticated data (AAD). (Optional)
     * @return string The base64-encoded encrypted payload.
     */
    public function encrypt(
        string $data,
        array $keyContext,
        ?string $associatedData = null,
    ): string {
        $keyPair = $this->createDataKey($keyContext);

        $key = base64_decode($keyPair['data_key']);
        $keyBlob = base64_decode($keyPair['encrypted_keys']);
        $prefixLenBuffer = self::encodeU32Leb128(strlen($keyBlob));
        $iv = random_bytes(12);

        $result = self::aesGcmEncrypt($data, $key, $iv, $associatedData);

        $combined = $result['iv'] . $result['tag'] . $prefixLenBuffer . $keyBlob . $result['ciphertext'];
        return base64_encode($combined);
    }

    /**
     * Decrypt data that was previously encrypted using the encrypt method.
     *
     * @param string $encryptedData The base64-encoded encrypted payload.
     * @param string|null $associatedData Additional authenticated data (AAD). (Optional)
     * @return string The decrypted plaintext.
     */
    public function decrypt(
        string $encryptedData,
        ?string $associatedData = null,
    ): string {
        $decoded = self::decodeEncryptedPayload($encryptedData);
        $dataKey = $this->decryptDataKey($decoded['keys']);

        $key = base64_decode($dataKey['data_key']);

        return self::aesGcmDecrypt(
            $decoded['ciphertext'],
            $key,
            $decoded['iv'],
            $decoded['tag'],
            $associatedData,
        );
    }

    // -- Crypto helpers --

    /**
     * AES-256-GCM encrypt.
     *
     * @return array{ciphertext: string, iv: string, tag: string}
     */
    private static function aesGcmEncrypt(
        string $plaintext,
        string $key,
        string $iv,
        ?string $aad,
    ): array {
        $tag = '';
        $ciphertext = openssl_encrypt(
            $plaintext,
            'aes-256-gcm',
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag,
            $aad ?? '',
            16,
        );

        if ($ciphertext === false) {
            throw new \RuntimeException('AES-GCM encryption failed');
        }

        return ['ciphertext' => $ciphertext, 'iv' => $iv, 'tag' => $tag];
    }

    /**
     * AES-256-GCM decrypt.
     */
    private static function aesGcmDecrypt(
        string $ciphertext,
        string $key,
        string $iv,
        string $tag,
        ?string $aad,
    ): string {
        $plaintext = openssl_decrypt(
            $ciphertext,
            'aes-256-gcm',
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag,
            $aad ?? '',
        );

        if ($plaintext === false) {
            throw new \RuntimeException('AES-GCM decryption failed');
        }

        return $plaintext;
    }

    /**
     * Encode a 32-bit unsigned integer as LEB128.
     */
    private static function encodeU32Leb128(int $value): string
    {
        if ($value < 0 || $value > 0xFFFFFFFF) {
            throw new \InvalidArgumentException('Value must be a 32-bit unsigned integer');
        }

        $encoded = '';
        do {
            $byte = $value & 0x7F;
            $value >>= 7;
            if ($value !== 0) {
                $byte |= 0x80;
            }
            $encoded .= chr($byte);
        } while ($value !== 0);

        return $encoded;
    }

    /**
     * Decode an unsigned LEB128-encoded 32-bit integer.
     *
     * @return array{0: int, 1: int} [value, bytesConsumed]
     */
    private static function decodeU32Leb128(string $buf): array
    {
        $res = 0;
        $bit = 0;
        $len = strlen($buf);

        for ($i = 0; $i < $len; $i++) {
            if ($i > 4) {
                throw new \InvalidArgumentException('LEB128 integer overflow');
            }
            $b = ord($buf[$i]);
            $res |= ($b & 0x7F) << (7 * $bit);
            if (($b & 0x80) === 0) {
                return [$res, $i + 1];
            }
            $bit++;
        }

        throw new \InvalidArgumentException('LEB128 integer not found');
    }

    /**
     * Extract IV, tag, keyBlob, and ciphertext from a base64 payload.
     *
     * Format: [IV:12b][TAG:16b][LEB128 Length][keyBlob][ciphertext]
     *
     * @return array{iv: string, tag: string, keys: string, ciphertext: string}
     */
    private static function decodeEncryptedPayload(string $encryptedDataB64): array
    {
        $payload = base64_decode($encryptedDataB64, true);
        if ($payload === false) {
            throw new \InvalidArgumentException('Base64 decoding failed');
        }

        $iv = substr($payload, 0, 12);
        $tag = substr($payload, 12, 16);
        [$keyLen, $lebLen] = self::decodeU32Leb128(substr($payload, 28));
        $keysIndex = 28 + $lebLen;
        $keysEnd = $keysIndex + $keyLen;
        $keysSlice = substr($payload, $keysIndex, $keyLen);
        $keys = base64_encode($keysSlice);
        $ciphertext = substr($payload, $keysEnd);

        return ['iv' => $iv, 'tag' => $tag, 'keys' => $keys, 'ciphertext' => $ciphertext];
    }
}
