<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace WorkOS;

use WorkOS\Service\AdminPortal;
use WorkOS\Service\ApiKeys;
use WorkOS\Service\AuditLogs;
use WorkOS\Service\Authorization;
use WorkOS\Service\Connect;
use WorkOS\Service\DirectorySync;
use WorkOS\Service\Events;
use WorkOS\Service\FeatureFlags;
use WorkOS\Service\Groups;
use WorkOS\Service\MultiFactorAuth;
use WorkOS\Service\OrganizationDomains;
use WorkOS\Service\Organizations;
use WorkOS\Service\Pipes;
use WorkOS\Service\Radar;
use WorkOS\Service\SSO;
use WorkOS\Service\UserManagement;
use WorkOS\Service\UserManagementOrganizationMembershipGroups;
use WorkOS\Service\Webhooks;
use WorkOS\Service\Widgets;

class WorkOS
{
    private static ?string $apiKey = null;
    private static ?string $clientId = null;
    private ?HttpClient $httpClient = null;

    public static function getApiKey(): ?string
    {
        return self::$apiKey;
    }

    public static function setApiKey(?string $key): void
    {
        self::$apiKey = $key;
    }

    public static function getClientId(): ?string
    {
        return self::$clientId;
    }

    public static function setClientId(?string $id): void
    {
        self::$clientId = $id;
    }
    private ?Service\ApiKeys $apiKeys = null;
    private ?Service\MultiFactorAuth $multiFactorAuth = null;
    private ?Service\Connect $connect = null;
    private ?Service\Authorization $authorization = null;
    private ?Service\SSO $sso = null;
    private ?Service\Pipes $pipes = null;
    private ?Service\DirectorySync $directorySync = null;
    private ?Service\Events $events = null;
    private ?Service\FeatureFlags $featureFlags = null;
    private ?Service\OrganizationDomains $organizationDomains = null;
    private ?Service\Organizations $organizations = null;
    private ?Service\Groups $groups = null;
    private ?Service\AdminPortal $adminPortal = null;
    private ?Service\Radar $radar = null;
    private ?Service\UserManagement $userManagement = null;
    private ?Service\UserManagementOrganizationMembershipGroups $userManagementOrganizationMembershipGroups = null;
    private ?Service\Webhooks $webhooks = null;
    private ?Service\Widgets $widgets = null;
    private ?Service\AuditLogs $auditLogs = null;

    public function __construct(
        ?string $apiKey = null,
        ?string $clientId = null,
        string $baseUrl = 'https://api.workos.com',
        int $timeout = 60,
        int $maxRetries = 3,
        ?\GuzzleHttp\HandlerStack $handler = null,
        ?string $userAgent = null,
    ) {
        $apiKey ??= getenv('WORKOS_API_KEY') ?: self::$apiKey ?? '';
        $clientId ??= getenv('WORKOS_CLIENT_ID') ?: self::$clientId;
        $this->httpClient = new HttpClient($apiKey, $clientId, $baseUrl, $timeout, $maxRetries, $handler, $userAgent);
    }

    public function apiKeys(): ApiKeys
    {
        return $this->apiKeys ??= new Service\ApiKeys($this->httpClient);
    }

    public function multiFactorAuth(): MultiFactorAuth
    {
        return $this->multiFactorAuth ??= new Service\MultiFactorAuth($this->httpClient);
    }

    public function connect(): Connect
    {
        return $this->connect ??= new Service\Connect($this->httpClient);
    }

    public function authorization(): Authorization
    {
        return $this->authorization ??= new Service\Authorization($this->httpClient);
    }

    public function sso(): SSO
    {
        return $this->sso ??= new Service\SSO($this->httpClient);
    }

    public function pipes(): Pipes
    {
        return $this->pipes ??= new Service\Pipes($this->httpClient);
    }

    public function directorySync(): DirectorySync
    {
        return $this->directorySync ??= new Service\DirectorySync($this->httpClient);
    }

    public function events(): Events
    {
        return $this->events ??= new Service\Events($this->httpClient);
    }

    public function featureFlags(): FeatureFlags
    {
        return $this->featureFlags ??= new Service\FeatureFlags($this->httpClient);
    }

    public function organizationDomains(): OrganizationDomains
    {
        return $this->organizationDomains ??= new Service\OrganizationDomains($this->httpClient);
    }

    public function organizations(): Organizations
    {
        return $this->organizations ??= new Service\Organizations($this->httpClient);
    }

    public function groups(): Groups
    {
        return $this->groups ??= new Service\Groups($this->httpClient);
    }

    public function adminPortal(): AdminPortal
    {
        return $this->adminPortal ??= new Service\AdminPortal($this->httpClient);
    }

    public function radar(): Radar
    {
        return $this->radar ??= new Service\Radar($this->httpClient);
    }

    public function userManagement(): UserManagement
    {
        return $this->userManagement ??= new Service\UserManagement($this->httpClient);
    }

    public function userManagementOrganizationMembershipGroups(): UserManagementOrganizationMembershipGroups
    {
        return $this->userManagementOrganizationMembershipGroups ??= new Service\UserManagementOrganizationMembershipGroups($this->httpClient);
    }

    public function webhooks(): Webhooks
    {
        return $this->webhooks ??= new Service\Webhooks($this->httpClient);
    }

    public function widgets(): Widgets
    {
        return $this->widgets ??= new Service\Widgets($this->httpClient);
    }

    public function auditLogs(): AuditLogs
    {
        return $this->auditLogs ??= new Service\AuditLogs($this->httpClient);
    }

    // @oagen-ignore-start — non-spec service properties (hand-maintained)
    private ?Passwordless $passwordless = null;
    private ?Vault $vault = null;
    private ?WebhookVerification $webhookVerification = null;
    private ?Actions $actions = null;
    private ?SessionManager $sessionManager = null;
    private ?PKCEHelper $pkce = null;
    // @oagen-ignore-end

    // @oagen-ignore-start — non-spec service accessors (hand-maintained)

    public function passwordless(): Passwordless
    {
        return $this->passwordless ??= new Passwordless($this->httpClient);
    }

    public function vault(): Vault
    {
        return $this->vault ??= new Vault($this->httpClient);
    }

    public function webhookVerification(): WebhookVerification
    {
        return $this->webhookVerification ??= new WebhookVerification($this->httpClient);
    }

    public function actions(): Actions
    {
        return $this->actions ??= new Actions($this->httpClient);
    }

    public function sessionManager(): SessionManager
    {
        return $this->sessionManager ??= new SessionManager($this->httpClient);
    }

    public function pkce(): PKCEHelper
    {
        return $this->pkce ??= new PKCEHelper($this->httpClient);
    }
    // @oagen-ignore-end
}
