name: Lint

on:
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: "8.2"
          tools: "composer"

      - name: Cache Composer packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.2-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction

      - name: Lint and formatting
        run: |
          composer run-script format-check
