name: Lint

on:
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: "8.2"
          tools: "composer"

      - name: Cache Composer packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.2-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction

      - name: Lint and formatting
        run: |
          composer run-script format-check
